DeveloperAcademy-POSTECH/MacC-Team-HappyAnding

- HappyAnding/HappyAnding.xcodeproj/project.pbxproj
- HappyAnding/HappyAnding/Extensions/Font+Extension.swift
- closes #19
- 폰트 디자인 요소를 적용하기 위한 익스텐션 함수 구현
- 디자인 시스템과 통일하기 위하여 UpperCamelCase로 작성했습니다.
|iPhone 14 Pro|
|:---:|
|<img src = "https://user-images.githubusercontent.com/41153398/197060771-13da167a-dd9a-4780-ba31-0cfdd037e235.png" width=300>
> [Feat] Add font extension

- HappyAnding/HappyAnding/Views/Components/ShortcutCell.swift
- closes #12
- 단축어 셀을 제작했습니다.
|<img src = "https://user-images.githubusercontent.com/68676844/197054189-a5f17020-a093-4696-a82f-3bf0bc2f790f.png" width = 250> |<img src = "https://user-images.githubusercontent.com/68676844/197050579-3d7ca630-427d-4073-a926-b4b9305782b8.png" width = 250>|<img src = "https://user-images.githubusercontent.com/68676844/197064480-48823daa-faee-4445-a44a-dabde7189812.png" width = 250>|
- iPhone Pro Max 화면은 List에서 해당 뷰를 호출했을 때 보이는 화면입니다.
- rectangle에 counerRadius를 설정하고, border를 주게 되면 다음과 같은 현상이 발생합니다.
-> overlay를 사용하여 border가 짤리지 않도록 구현하였습니다.
- ZStack에 Rectangle과 HStack을 넣어 구현하였더니 Description이 길어질 때 다음과 같은 이슈가 발생했습니다.
-> HStack에 background로 RoundedRectangle을 넣고, HStack에 vertical padding을 주는 방법으로 Dynamic …
> [Feat] create ShortcutCell

- HappyAnding/HappyAnding/Extensions/Font+Extension.swift
- HappyAnding/HappyAnding/Views/Components/UserCurationCell.swift
- closes #14
- UserCurationCell UI 구현
- subtitle 유무에 따른 높이 변경
- 포함되는 단축어 수에 따라 화면에 표시되는 아이콘 수 변경
|iPhone 13 - subtitle 유무|iPhone 13 - 아이콘 수 변경|
|:---:|:---:|
|<img src = "https://user-images.githubusercontent.com/41153398/197212773-0ece8f2f-9b57-4ab5-b825-1d584e3f97af.png" width=300>|<img src = "https://user-images.githubusercontent.com/41153398/197213631-cb49682b-b4fd-454d-80d2-3ef8c9839148.png" width=300>|
> [Feat] Create UserCurationCell

- HappyAnding/HappyAnding.xcodeproj/project.pbxproj
- HappyAnding/HappyAnding/Views/ShortcutTestModel.swift
Co-authored-by: JIWON1923 <zest1923@gmail.com>
Co-authored-by: JMM00 <cjjunn0827@gmail.com>
- closes #15
- ShortcutCell 을 위한 테스트 모델 생성
- UserCurationCell을 위한 테스트 모델 생성
더미데이터가 필요한 뷰에서 
let shortcuts = Shortcut.fetchData(number: /*원하는 갯수*/)
let userCurations = UserCuration.fetchData(number: /*원하는 갯수*/) 
와 같이 함수를 호출해서 사용해주세요.
|iPhone 13|
|:---:|
|<img src = "https://user-images.githubusercontent.com/41153398/197247967-42c1ca16-d789-46a2-b7b7-5a1b2b427fe6.png" width = 300 >|
> [Feat] dummy data 생성

- HappyAnding/HappyAnding.xcodeproj/project.pbxproj
- HappyAnding/HappyAnding/Model/Category.swift
- HappyAnding/HappyAnding/Model/SectionType.swift
- HappyAnding/HappyAnding/Views/Components/ListShortcutView.swift
- closes #47
- enum Category와 SelectionType을 만들었습니다.
- 해당 부분 모두 확장가능성이 존재!
- UI 변경은 없습니다.
- SelectionType은 다운로드에서 접근하는지, 사랑받는 앱에서 접근하는지 알려주는 것입니다!
- #49
> [Feat] 카테고리 및 selection type 열거형 만들기

- HappyAnding/HappyAnding/Extensions/Font+Extension.swift
- closes #64
Font Extension 수정 : LargeTitle, Title1, Title2, Headline, Subtitle Weight 수정
> [Feat] #64 Font Extension 수정

- HappyAnding/HappyAnding.xcodeproj/project.pbxproj
- HappyAnding/HappyAnding/Extensions/Navigationbar+Extension.swift
- HappyAnding/HappyAnding/Views/MyPageViews/SettingView.swift
- HappyAnding/HappyAnding/Views/TabView/ShortcutTabView.swift
- closes #57
- SettingView UI 구현
- 네비게이션바 아이템 색상 변경을 위한 함수 구현 (가장 최상단 뷰 init()에서 선언하여 사용
- MyPageView가 수정이 필요하다고 하여 pr을 닫고 해당 뷰에서 적용했던 탭바 컬러 변경 코드를 여기서 추가했습니다.
|iPhone 13|
|:---:|
|<img src = "https://user-images.githubusercontent.com/41153398/197592147-f8b8e7e4-6cce-4d87-af6a-f13a2ea38bab.png" width = 300>|
> [Feat] SettingView UI 구현

- HappyAnding/HappyAnding.xcodeproj/project.pbxproj
- HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/CategoryView.swift
- HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/ListCategoryView.swift
- closes #71
- 카테고리 더보기눌렀을 때 나오는 뷰 제작
- 더보기 버튼 클릭시 해당 뷰와 연결
- 카테고리 클릭 시 ListShortcutView로 연결
|<img src = "https://user-images.githubusercontent.com/68676844/197809827-95c78b12-67ed-4c32-9e95-eed9d5f597b8.png" width = 250>|<img src = "https://user-images.githubusercontent.com/68676844/197809804-3f85e213-8990-4f6b-a6db-403989a40060.png" width = 250>|<img src = "https://user-images.githubusercontent.com/68676844/197809813-60e27b53-4b3f-4bce-aefe-bc0788c154d3.png" width = 250>|
- 그린의 코드를 살짝 훔쳐봤어요~
> [Feat] ListCategoryView

- HappyAnding/HappyAnding/Model/SectionType.swift
- HappyAnding/HappyAnding/Views/Components/ListShortcutView.swift
- HappyAnding/HappyAnding/Views/Components/MyShortcutCardListView.swift
- closes #75
- 내 단축어 페이지 제작
- SectionType 유형 추가
|<img src = "https://user-images.githubusercontent.com/68676844/198002546-1dcfc7cd-904b-4b02-bc8c-438e24cbccb6.png" width = 250>|<img src = "https://user-images.githubusercontent.com/68676844/198002558-2249e50d-c617-48df-948d-a3e1d4830ca4.png" width = 250>|<img src = "https://user-images.githubusercontent.com/68676844/198002637-74e01113-b961-482a-8149-841b9c97ef41.png" width = 250>|
> [Feat] MyWritingShortcutView

- HappyAnding/HappyAnding/Assets.xcassets/Colors/SystemColors/Background.colorset/Contents.json
- HappyAnding/HappyAnding/Assets.xcassets/Colors/SystemColors/White.colorset/Contents.json
- HappyAnding/HappyAnding/Assets.xcassets/Colors/TextColors/Gray1.colorset/Contents.json
- HappyAnding/HappyAnding/Assets.xcassets/Colors/TextColors/Gray2.colorset/Contents.json
- HappyAnding/HappyAnding/Assets.xcassets/Colors/TextColors/Gray3.colorset/Contents.json
- HappyAnding/HappyAnding/Assets.xcassets/Colors/TextColors/Gray4.colorset/Contents.json
- HappyAnding/HappyAnding/Assets.xcassets/Colors/TextColors/Gray5.colorset/Contents.json
- HappyAnding/HappyAnding/Extensions/Font+Extension.swift
- closes #70 
DarkMode Color 설정 추가 :SystemColors/Background, White & TextColors / Gray1, Gray2, Gray3, Gray4, Gray5
> [Feat] #70 Extension DarkMode Color 추가

- HappyAnding/HappyAnding/Model/Category.swift
- HappyAnding/HappyAnding/Views/Components/ValidationCheckTextField.swift
- HappyAnding/HappyAnding/Views/WriteShortcutViews/CategoryModalView.swift
- HappyAnding/HappyAnding/Views/WriteShortcutViews/IconModalView.swift
- HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutTagView.swift
- HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutTitleView.swift
- HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutdescriptionView.swift
- closes #68 
- closes #25 
- closes #27 
- closes #67 
- 단축어 작성 관련한 뷰들 화면 그리고 연결했습니다.
- 단축어 작성이 fullscreencover로 진행되기 때문에 맨 첫페이지에 짭내비게이션바가 있습니다.
- 🚨 내비게이션 백버튼의 텍스트 지우고 싶어요.
- 🚨 keyboard avoidance 이슈 있습니다.
https://user-images.githubusercontent.com/76623853/198018415-948155b6-630d-4d46-b125-0f54b643cfa1.mp4
> [Feat] WriteShortcutViews UI 및 내비게이션

- HappyAnding/HappyAnding.xcodeproj/project.pbxproj
- HappyAnding/HappyAnding/Views/Components/AdminCurationCell.swift
- HappyAnding/HappyAnding/Views/Components/CurationListView.swift
- HappyAnding/HappyAnding/Views/ExploreCurationViews/ExploreCurationView.swift
- closes #94
- ExploreCurationView UI 제작
- CurationListView 생성
- AdminCurationCell 수정
|![Simulator Screen Shot - iPhone SE (3rd generation) - 2022-10-27 at 07 38 23](https://user-images.githubusercontent.com/94854258/198155610-1a82ec17-fa3b-4bd6-ae0e-b00fa0e7bf6f.png)|![Simulator Screen Shot - iPhone 14 - 2022-10-27 at 07 37 38](https://user-images.githubusercontent.com/94854258/198155702-52b842c7-1797-4e08-a109-856832d50e72.png)|![Simulator Screen Shot - iPhone 14 Pro Max - 2022-10-27 at 07 38 57](https://user-images.githubusercontent.com/94854258/198155774-7474d8f7-e7a0-49ee-abac-1809b4cf7207.png)|
|![Simulator Screen Shot - iPhone SE (3rd generation) - 2022-10-27 at 07 38 …
> [Feat] ExploreCurationView UI 제작

- HappyAnding/HappyAnding/Views/TabView/ShortcutTabView.swift
- closes #7 
탭바 바 틴트 컬러 White로 변경
탭바 선택안된 아이콘 컬러 Gray2로 변경
탭바 보더라인 컬러 변경

> [Style] 탭바 컬러 변경

- HappyAnding/HappyAnding.xcodeproj/project.pbxproj
- HappyAnding/HappyAnding/Extensions/Application+Extension.swift
- HappyAnding/HappyAnding/Views/Components/MyShortcutCardListView.swift
- HappyAnding/HappyAnding/Views/Components/ValidationCheckTextField.swift
- HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutTagView.swift
- HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutTitleView.swift
- MyShortcutCardView에서 WriteShortcutTitleView로 연결되는 내비게이션 수정했습니다.
- 텍스트 필드 밖을 탭하면 키보드가 내려가는 기능 추가했습니다.
- WriteShortcutTitleView의 back button 스타일 수정하고 내비게이션 타이틀 삭제했습니다.
- WriteShortcutTitleView에서 키보드가 열리면 다음버튼이 따라 올라가는 현상 수정했습니다.
> [Feat] WriteShortcutViews에 관련된 수정사항

- HappyAnding/HappyAnding/Views/Components/ShortcutCell.swift
- HappyAnding/HappyAnding/Views/WriteCurationViews/CheckBoxShortcutCell.swift
- HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationSetView.swift
- closes #108
- 에러 해결
- 배열 인덱스가 벗어나 발생한 에러
- subtitle이 아닌 Description가 보이는 이슈 수정
> [Fix] 큐레이션 작성 뷰 에러 해결

- HappyAnding/HappyAnding.xcodeproj/project.pbxproj
- HappyAnding/HappyAnding/Model/Curation.swift
- HappyAnding/HappyAnding/ViewModel/ShortcutsZipViewModel.swift
- HappyAnding/HappyAnding/Views/ExploreCurationViews/ExploreCurationView.swift
- HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/ExploreShortcutView.swift
- HappyAnding/HappyAnding/Views/TabView/ShortcutTabView.swift
- HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationInfoView.swift
- closes #114 
- Shortcut 관련 ViewModel 추가
- Shortcut 관련 ViewModel 뷰에 적용 (ExploreShortcutView)
- Curation 관련 ViewModel 추가
- Curation 관련 ViewModel 뷰에 적용 (ExploreCurationView)
- 변경 파일
- ShortcutsZipViewModel.swift (새로 추가)
- Views/ShortcutTabView.swift
- Views/ExploreShortcutView.swift
- Views/ExploreCurationView.swift
- Views/WriteCurationInfoView.swift
- Models/Curation.swift
- 변경된 파일 잘 확인해주세용
- UI 변경 사항은 없어서 따로 스크린샷은 첨부하지않았습니다.
> [Feat] ShortcutsZipViewModel 관련 Shortcut, Curtion 로직 및 데이터 변경

- HappyAnding/HappyAnding/Extensions/Navigationbar+Extension.swift
- HappyAnding/HappyAnding/Views/ExploreCurationViews/ReadAdminCurationView.swift
Navigation Bar Color 및 Back Button 수정
- closes #118 
- ReadAdminCurationView Navigation Bar Custom Back Button 추가
- 전체 Navigation Bar Color -> White로 변경
|1|2|3|
|![Simulator Screen Shot - iPhone 14 - 2022-11-02 at 15 35 38](https://user-images.githubusercontent.com/91725382/199417170-7cbaee4e-34ff-4804-8515-6a2ab5d5b4c7.png)|![Simulator Screen Shot - iPhone 14 - 2022-11-02 at 15 35 25](https://user-images.githubusercontent.com/91725382/199417189-bccf4477-e3d1-467e-a50e-9855a55f59cc.png)|![Simulator Screen Shot - iPhone 14 - 2022-11-02 at 15 35 16](https://user-images.githubusercontent.com/91725382/199417197-2c22e02e-7c38-4086-aa82-e6a785c5fcb5.png)|
> [Fix] #118 Navigation Bar Color 및 Back Button 수정

- HappyAnding/HappyAnding/Views/Components/MyShortcutCardListView.swift
- HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutView.swift
- HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutTagView.swift
- HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutTitleView.swift
- HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutdescriptionView.swift
- closes #111
- 단축어 수정 기능 구현
- State를 이용하여 shortcut을 처리하였습니다.
- 새로운 뷰를 만든 것이 아니므로, 시뮬레이션 비교는 생략하겠습니다.
|기존 단축어 편집|새로운 단축어 등록|
|---|---|
https://user-images.githubusercontent.com/68676844/199317055-d7e8f0fb-340e-410a-90bc-236cbfd51b48.mov
- 지금 편집화면 종료되고 뷰 업데이트 안 돼요!
- 뷰모델 적용되면 해결될 것 같긴해유
> [Feat] EditShortcutView

- HappyAnding/HappyAnding/Views/Components/ListShortcutView.swift
- HappyAnding/HappyAnding/Views/Components/ShortcutCell.swift
- HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/DownloadRankView.swift
- HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutHeaderView.swift
- HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutView.swift
ReadShortcutView 공유버튼 기능 구현
- closes #125 
- 공유 버튼 기능 구현
- 같은 뷰 작업할 거 하면서 하나씩 추가하다가 어쩌다보니 다른 작업도 계속 같은 브랜치에 추가로 했습니다. 죄송;
- 추가 작업 내용은 댓글로 스샷 함께 첨부하였습니다.
- 확인 같이 해주세요 ~~~
|잘못된 링크|맞는 링크|
|:---:|:---:|
|![Simulator Screen Shot - iPhone 14 - 2022-11-02 at 19 51 44](https://user-images.githubusercontent.com/91725382/199471695-ff502d4c-1062-45ab-9a87-54dc57692f4a.png)|![Simulator Screen Shot - iPhone 14 - 2022-11-02 at 19 51 57](https://user-images.githubusercontent.com/91725382/199471708-818f0ac9-5afa-4860-8564-8c6454086c4c.png)|
> [Feat] #125 ReadShortcutView 공유버튼 기능 구현

- HappyAnding/HappyAnding/Views/Components/UserCurationListView.swift
- HappyAnding/HappyAnding/Views/ExploreCurationViews/ReadUserCurationView.swift
- HappyAnding/HappyAnding/Views/WriteCurationViews/CheckBoxShortcutCell.swift
- HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationInfoView.swift
- HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationSetView.swift
- closes #112
- 큐레이션 편집 기능 구현
- 네이게이션바 타이틀 수정
- 새로운 UI가 생긴 상황이 아니어서 화면녹화로 대체합니다.
https://user-images.githubusercontent.com/68676844/199525378-b6587ace-de3d-4124-8d02-09d9ba6bc86b.mov
- 추후 엘리가 진행되어야하는 작업이 있어서 빠른 확인 부탁드려유
> [Feat] 큐레이션 편집 기능 구현

- HappyAnding/HappyAnding/Views/ExploreCurationViews/ReadUserCurationView.swift
- HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutView.swift
- closes #135
- closes #132
- 삭제 버튼 색상 변경
- 삭제 alert 설정
|navigaion bar item|alert|
|---|---|
|<img src = "https://user-images.githubusercontent.com/68676844/199589754-32332942-1c94-4d51-9e94-148195542857.png" width = 250> |<img src = "https://user-images.githubusercontent.com/68676844/199589892-653d6da5-a883-49aa-a8ca-67a72744a128.png" width = 250>|
> [Feat] 삭제 Alert 및 색상 변경

- HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutContentView.swift
- closes #117
- 카테고리 출력 뷰를 VStack에서 HStack으로 변경하였습니다.
> [Feat] 단축어 상세 뷰 카테고리 UI 변경

- HappyAnding/HappyAnding/Model/FirebaseService.swift
- HappyAnding/HappyAnding/Model/User.swift
- HappyAnding/HappyAnding/Views/ExploreCurationViews/ExploreCurationView.swift
- HappyAnding/HappyAnding/Views/ExploreCurationViews/ReadUserCurationView.swift
- HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/ExploreShortcutView.swift
- HappyAnding/HappyAnding/Views/MyPageViews/MyPageView.swift
- HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutContentView.swift
- HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutView.swift
- HappyAnding/HappyAnding/Views/SignInViews/WriteNicknameView.swift
- HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationInfoView.swift
- HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutTagView.swift
- 닉네임 중복확인 함수 추가되었습니다.
- User 모델 변경되었습니다.
- shortcut과 curation 작성시 작성자 id가 추가되어 저장됩니다.
- 내 단축어, 내 큐레이션 보기 연결되었습니다.
- ReadShortcutView, ReadUserCurationView에서 편집 버튼 나오는 조건 추가했습니다.
- 중복확인 후 닉네임 변경해도 시작하기 누를 수 있는 점 수정해야 할 것 같습니다.
- 닉네임 글자 수 제한 조건도 추가되어야 할 것 같아요.
- 현재 로그인된 유저 정보를 global하게 저장하여 사용하는 것이 좋을까요?
> [Feat] User 모델 변경 및 함수 추가

- HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationSetView.swift
> Write curation set view/navigation back button

- HappyAnding/HappyAnding.xcodeproj/project.pbxproj
- HappyAnding/HappyAnding/Views/WriteShortcutViews/IconModalView.swift
- closes #143
Icon SF Symol 변경
|수정 전|Light Mode|Dark Mode|
|![Simulator Screen Shot - iPhone 14 - 2022-11-03 at 17 29 06](https://user-images.githubusercontent.com/103024869/199676078-737a9475-85a7-43f1-8a65-1fda6ecffae4.png)|![Simulator Screen Shot - iPhone 14 - 2022-11-03 at 17 26 38](https://user-images.githubusercontent.com/103024869/199675858-370e8284-af21-4202-ba3b-5f738f0a5b22.png)|![Simulator Screen Shot - iPhone 14 - 2022-11-03 at 17 26 52](https://user-images.githubusercontent.com/103024869/199675904-0f624ca4-4d9a-4d6d-9f0a-79d58220050e.png)|
> [Feat] #143 - Icon Symbol 변경

- HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutTagView.swift
- closes #154 
- onSubmit이 아닌 onChange에서 처리하였습니다.
- 현재 키보드가 사라질 때, 해당 앱이 등록되도록 설정되어있음니담
- 한번씩 실행해보시는 걸 추천드려요 (어떤 에러가 있을지 모름)
https://user-images.githubusercontent.com/68676844/199725284-4eb538fc-fd36-4aee-af42-0a2c9838bdfb.MP4
> [Feat] 연관된 앱 입력 방식 수정

- HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationInfoView.swift
- closes #153 
- 화면에 탭 제스쳐 추가했습니다.
https://user-images.githubusercontent.com/76623853/199724971-8fc7ab3b-41ad-4901-a4c4-94ed2d245507.mp4
> [Fix] 큐레이션 설명 작성 화면에서 키보드 내리기

- HappyAnding/HappyAnding/Model/Category.swift
- HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/CategoryView.swift
- HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/ListCategoryView.swift
- HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutContentView.swift
- closes #157 
- closes #158 
- closes #159 
- 카테고리 별 세부 설명을 변경했습니다.
- HiFi 디자인이 변경됨에 따라 ListCategoryView 및 CategoryView를 수정했습니다.
- 메인뷰에 있는 카테고리 모아보기와 비슷한 형태로 UI가 업데이트 되었습니다.
- 단축어가 많이 있을법한 카테고리가 메인에서 바로 보이도록 변경되었습니다.
1. 카테고리 별 세부 설명
3. ListCategoryView4. 
5. CategoryView
> [Feat] Category 관련 뷰 디자인 업데이트 

- HappyAnding/HappyAnding/ViewModel/ShortcutsZipViewModel.swift
- HappyAnding/HappyAnding/Views/ExploreCurationViews/ExploreCurationView.swift
- HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/ExploreShortcutView.swift
- HappyAnding/HappyAnding/Views/MyPageViews/MyPageView.swift
- HappyAnding/HappyAnding/Views/TabView/TabRouter.swift
- #163 
- ExploreShortcutView 관련 뷰모델 적용
- ExploreCurationView 관련 뷰모델 적용
- MyPageView 관련 뷰모델 적용
- UI 관련 작업 아니라 따로 추가하지 않았습니다!
> Shortcuts zip view model

- HappyAnding/HappyAnding/Views/Components/ListShortcutView.swift
- HappyAnding/HappyAnding/Views/TabView/ShortcutTabView.swift
- closes #146 
- 탭바 컬러 변경
- 사랑받는 단축어 디테일뷰 설명 텍스트 변경
||iPhone 14||
||![simulator_screenshot_C22ABDAA-CCCF-4194-B384-ED51E944350B](https://user-images.githubusercontent.com/91725382/199685545-b3f42e0b-4c96-4c55-9526-ca8ce1abf22b.png)||
> [Fix] 탭바 외 기타 등등 UI 변경 요청 사항 반영

- HappyAnding/HappyAnding.xcodeproj/project.pbxproj
- HappyAnding/HappyAnding/Extensions/Date+Extension.swift
- HappyAnding/HappyAnding/Model/Curation.swift
- HappyAnding/HappyAnding/Model/Shortcuts.swift
- HappyAnding/HappyAnding/Views/Components/AdminCurationCell.swift
- HappyAnding/HappyAnding/Views/ExploreCurationViews/ReadAdminCurationView.swift
- HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationInfoView.swift
- HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationSetView.swift
- HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutTagView.swift
- HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutTitleView.swift
- HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutdescriptionView.swift
- closes #168
- Firebase에서 제공하는 Timestamp 객체를 이용하려고 했으나 해당 객체 사용 시 데이터모델이 codable에 순응하지 않아 Date()객체를 String 값으로 변환하여 저장하도록 구현
- 내 단축어, 내 큐레이션 불러오는 함수에서 date/dateTime을 기준으로 정렬하여 불러오기 위해서 구현
- yyyyMMddHHmmss 형태로 저장 (년월일시분초)
화면 상의 변경 점 없어서 생략
> [Feat] 데이터 모델 서버시간 반영

- HappyAnding/HappyAnding/Model/FirebaseService.swift
- HappyAnding/HappyAnding/Views/ExploreCurationViews/ReadUserCurationView.swift
- HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutView.swift
- closes #172
- 삭제함수 연결
- 삭제 후 뷰 dismiss
https://user-images.githubusercontent.com/68676844/199818031-4eb52b61-a008-4d71-84e7-d565cd788c4e.mov
- 삭제 후 값 변경되면 뷰 상태 변경돼야해요!
> [Feat] 삭제함수 연결

- HappyAnding/HappyAnding/Views/Components/ListShortcutView.swift
- HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/CategoryView.swift
- HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/ListCategoryView.swift
- closes #165
- 카테고리에서 접근할 때, ListShortcutView로 연결됩니다.
https://user-images.githubusercontent.com/68676844/199760495-d575be53-c444-47b5-8715-52c8ee112d78.mp4
- 쉽게 봤다가 큰코다쳤네요;;
> [Feat] #165 - update explorecategoryView

- HappyAnding/HappyAnding/Views/ExploreCurationViews/ReadAdminCurationView.swift
- closes #170
- 뚱뚱네비게이션을 변경했습니다.
- (셀에서 다운로드 버튼이 클릭되지 않았던 이슈는 파이어베이스 구조 변경으로 일어난 작은 사건이었습니다)
- 통일성을 위해 스크롤 인디케이터를 삭제했습니다./
> [Fix] Admin curation view 오류 수정

- HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutContentView.swift
- HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutTagView.swift
- closes #176
- 필요한 앱을 필수 입력이 아닌 선택 구현으로 변경!
- 아무런 글이 없는 경우, 해당 헤더를 숨기는 것은 어때보이시나유?
> [Feat] 연관앱 입력 방식 수정

- HappyAnding/HappyAnding.xcodeproj/project.pbxproj
- HappyAnding/HappyAnding/ViewModel/ShortcutsZipViewModel.swift
- HappyAnding/HappyAnding/Views/ExploreCurationViews/ReadUserCurationView.swift
- HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutView.swift
- HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationInfoView.swift
- HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutTagView.swift
- HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutTitleView.swift
- HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutdescriptionView.swift
- #163 
- 숏컷 추가시 뷰에 바로 반영
- 큐레이션 추가시 뷰에 바로 반영
- 숏컷 삭제시 뷰 반영 추가
용량때문에 단축어 추가는 못 올렸습니다..
https://user-images.githubusercontent.com/91725382/199874108-970282c8-a663-4224-b44e-d6234ee1cb83.MP4
> [Feat] Shortcuts zip ViewModel 관련 작업 진행

- HappyAnding/HappyAnding/Model/Curation.swift
- HappyAnding/HappyAnding/Model/FirebaseService.swift
- HappyAnding/HappyAnding/Views/WriteCurationViews/CheckBoxShortcutCell.swift
- HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationSetView.swift
- closes #189 
- 좋아하는 단축어, 본인이 만든 단축어를 [shortcutcellmodel]로 가져오는 함수 작성했습니다.
- 중복제거하기 위해 shortcutcellmodel에 hashable 추가했습니다.
- 단축어 선택 10개 제한 조건도 추가했습니다 ~~~
> [Feat] 큐레이션 작성시 선택할 수 있는 단축어 제한

- HappyAnding/HappyAnding/Model/SectionType.swift
- HappyAnding/HappyAnding/Views/Components/CurationListView.swift
- HappyAnding/HappyAnding/Views/Components/ListShortcutView.swift
- HappyAnding/HappyAnding/Views/Components/MyShortcutCardListView.swift
- HappyAnding/HappyAnding/Views/ExploreCurationViews/ExploreCurationView.swift
- HappyAnding/HappyAnding/Views/ExploreCurationViews/ReadUserCurationView.swift
- HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationInfoView.swift
- closes #185 
- closes #186
- closes #191 
- 유저 큐레이션 블럭의 이름을 유저 스마트한 생활의 시작 -> 유저 큐레이션으로 변경
- WriteCurationInfoView에서 텍스트 필드 색상 변경
- UserCurationView Stickyheader 생성
|유저 큐레이션|텍스트필드|스티키헤더|
|<img width="576" alt="Screenshot 2022-11-04 at 16 44 16" src="https://user-images.githubusercontent.com/94854258/199919826-7446daf2-05ec-4979-8b68-06662d5c672c.png">|<img width="568" alt="Screenshot 2022-11-04 at 16 44 40" src="https://user-images.githubusercontent.com/94854258/199919883-e36433a9-ca98-412b-9562-15bffaae4f8c.png">|<img width="593" alt="Screenshot 2022-11-04 at 16 45 08" src="https://user-images.githubusercontent.com/94854258/199919971-8365340a-3f3e-4a39-b53f-e1d1e1ee4707.png">|
> [Feat] Design Minor Changes

- HappyAnding/HappyAnding/Views/Components/ValidationCheckTextField.swift
- closes #169 
- textfield가 optional이면 어떤 경우에도 valid하다 해줬던 탓입니다.
|작성안한경우|글자수초과한경우|
|:---:|:---:|
|![Simulator Screen Shot - iPhone 14 - 2022-11-04 at 16 14 51](https://user-images.githubusercontent.com/76623853/199916362-ed87e737-72ea-4c32-80ce-7d777d251ca9.png)|![Simulator Screen Shot - iPhone 14 - 2022-11-04 at 16 16 15](https://user-images.githubusercontent.com/76623853/199916388-bb1b523d-b20a-4ae2-9094-0d25acd2dda2.png)|
> [Fix] 글자수가 초과해도 저장되는 이슈

- HappyAnding/HappyAnding/ViewModel/ShortcutsZipViewModel.swift
- HappyAnding/HappyAnding/Views/Components/ListShortcutView.swift
- HappyAnding/HappyAnding/Views/Components/ShortcutCell.swift
- HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/LovedShortcutView.swift
- HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutContentView.swift
- HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutHeaderView.swift
- #163 
폴더 내부 firebase -> 뷰모델로 처리로 변경
> [Feat] ViewModel 뷰 처리

- HappyAnding/HappyAnding/Views/SignInViews/WriteNicknameView.swift
- closes #192
- 닉네임 글자 수에 따른 로직 변경
https://user-images.githubusercontent.com/68676844/199917519-d90da477-dcbc-46df-90d6-06a0dbf22e8b.mp4
> [Feat] 닉네임 글자수 제한

- HappyAnding/HappyAnding.xcodeproj/project.pbxproj
- HappyAnding/HappyAnding/Views/Components/ShortcutCell.swift
- HappyAnding/HappyAnding/Views/MyPageViews/MailView.swift
- HappyAnding/HappyAnding/Views/MyPageViews/MyPageView.swift
- HappyAnding/HappyAnding/Views/MyPageViews/SettingView.swift
- closes #198
- closes #201 
- MyPage View에서 Setting view 버튼 활성화
- 개발자에게 연락하기 클릭 시 메일 작성으로 이동
- 로그아웃 클릭 시 로그아웃 되도록 구현
https://user-images.githubusercontent.com/68676844/200111318-b913f381-f0d1-480c-9747-6399c94495e7.MP4
|화면1|화면2|
|---|---|
|<img src = "https://user-images.githubusercontent.com/68676844/200111387-09382049-7fa5-44cf-b79a-06d9027bedfc.png" width = 250>|<img src = "https://user-images.githubusercontent.com/68676844/200111380-c1e17709-2390-4179-a283-d44bcaac5f84.png" width = 250>|
- 시뮬레이터에서 확인하는 경우 다음과 같은 화면으로 보입니다 (메일을 보낼 수 없는 경우)
> [Feat] Setting view 기능 연결

- HappyAnding/HappyAnding.xcodeproj/project.pbxproj
- HappyAnding/HappyAnding/Assets.xcassets/Colors/TextColors/Grey005.colorset/Contents.json
- HappyAnding/HappyAnding/Assets.xcassets/Colors/TextColors/Grey010.colorset/Contents.json
- HappyAnding/HappyAnding/Assets.xcassets/Colors/TextColors/Grey020.colorset/Contents.json
- HappyAnding/HappyAnding/Assets.xcassets/Colors/TextColors/Grey030.colorset/Contents.json
- HappyAnding/HappyAnding/Assets.xcassets/Colors/TextColors/Grey040.colorset/Contents.json
- HappyAnding/HappyAnding/Assets.xcassets/Colors/TextColors/Grey050.colorset/Contents.json
- HappyAnding/HappyAnding/Assets.xcassets/Colors/TextColors/Grey060.colorset/Contents.json
- HappyAnding/HappyAnding/Assets.xcassets/Colors/TextColors/Grey070.colorset/Contents.json
- HappyAnding/HappyAnding/Assets.xcassets/Colors/TextColors/Grey080.colorset/Contents.json
- HappyAnding/HappyAnding/Extensions/Color+Extension.swift
- closes #122 
- 다크모드 사용을 위해 컬러셋 추가 및 변경
- 다크모드에서 semantic color 사용을 위한 세팅 추가
> [Feat] #122 - DarkMode Color 추가 및 세팅

- HappyAnding/HappyAnding.xcodeproj/project.pbxproj
- closes #161
다크모드 일대일 대응 오류로 인하여 disable처리했습니다.
다크모드와 라이트모드의 차이를 알기 어려워서 스크린샷은 생략합니다 0_<
> [Feat] #161 - DarkMode Disable

- HappyAnding/HappyAnding.xcodeproj/project.pbxproj
- HappyAnding/HappyAnding/Info.plist
- HappyAnding/HappyAnding/Views/SignInViews/PrivacyPolicyView.swift
- HappyAnding/HappyAnding/Views/SignInViews/SignInWithAppleView.swift
- closes #211
- 개인정보처리방침 클릭시 노션으로 이동
- 추후 버튼 위치나 디테일한 디자인 적용될 예정 (아마도?)
https://user-images.githubusercontent.com/68676844/200192629-e10f3c4c-dd8e-4b30-9160-97f376977e3e.mov
> [Feat] 회원가입 뷰, 개인정보처리방침

- HappyAnding/HappyAnding/Views/TabView/ShortcutTabView.swift
- closes #213
TabView에서 ViewModel 객체를 바로 전달해주어 문제를 해결했습니다.
추후 로그인 없이 둘러보기 기능이 생길 예정으로, 해당 로직의 개선이 필요합니다.
https://user-images.githubusercontent.com/68676844/200232167-0d426ffd-7e2a-4d69-996f-c9ff5f0054aa.mp4
> [Fix] 로그아웃 버그 해결

- HappyAnding/HappyAnding.xcodeproj/project.pbxproj
- HappyAnding/HappyAnding/Extensions/UINavigationContoller+Extension.swift
- HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/CategoryView.swift
- closes #203
- closes #217 
스와이프 제스처를 이용한 뒤로가기
메인화면에서 카테고리 상세 뷰 접근에 오류가 있어서 수정했습니다.
https://user-images.githubusercontent.com/68676844/200233356-d5f47a43-0ca1-4b4a-9db4-be0d2ff01cea.mov
> [Feat] 스와이프 제스처

- HappyAnding/HappyAnding/Assets.xcassets/Colors/SystemColors/Primary.colorset/Contents.json
- HappyAnding/HappyAnding/Extensions/Color+Extension.swift
- HappyAnding/HappyAnding/Views/Components/AdminCurationCell.swift
- HappyAnding/HappyAnding/Views/Components/MyShortcutCardView.swift
- HappyAnding/HappyAnding/Views/Components/ShortcutCell.swift
- HappyAnding/HappyAnding/Views/Components/UserCurationCell.swift
- HappyAnding/HappyAnding/Views/Components/UserCurationListView.swift
- HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutHeaderView.swift
- HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutView.swift
- HappyAnding/HappyAnding/Views/TabView/ShortcutTabView.swift
- HappyAnding/HappyAnding/Views/WriteCurationViews/CheckBoxShortcutCell.swift
- HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationInfoView.swift
- HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationSetView.swift
- HappyAnding/HappyAnding/Views/WriteShortcutViews/CategoryModalView.swift
- HappyAnding/HappyAnding/Views/WriteShortcutViews/IconModalView.swift
- HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutTagView.swift
- HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutTitleView.swift
- HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutdescriptionView.swift
- closes #206
- 다크모드에서 보이지 않는 컬러 대응
너무 많아서 생략합니다 ~
> [Feat] #206 - DarkMode Color 대응

- HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutdescriptionView.swift
- 한줄 설명 제한 길이 20에서 35로 변경합니다.
- 화면 변경사항 없습니다.
> [Feat] 단축어 한 줄 설명 제한 글자수 변경

- HappyAnding/HappyAnding/ViewModel/ShortcutsZipViewModel.swift
- 앱 종료 후 다시 실행 시 유저정보를 제대로 불러오지 못하는 오류 해결
> [FIX] 유저 정보 초기화 함수 선언

- HappyAnding/HappyAnding.xcodeproj/project.pbxproj
- HappyAnding/HappyAnding/Views/MyPageViews/SettingView.swift
- HappyAnding/HappyAnding/Views/MyPageViews/SettingViews/WithdrawalView.swift
- HappyAnding/HappyAnding/Views/SignInViews/UserAuth.swift
- HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationSetView.swift
- closes #232 
- 회원탈퇴 기능 구현(서버)
- 회원탈퇴 뷰 디자인 및 제작
- HiFI 디자인 적용
- 위 내용 어쩌고 글씨 클릭해도 체크표시 되도록 수정
- 현재 구현된 디자인이 없어서 직접 만들었습니다. 디자이너의 확인 및 수정이 필요합니다.
|다크 모드|라이트 모드|알럿|
|![IMG_6775](https://user-images.githubusercontent.com/94854258/200653714-0861870e-81e8-491d-bb6a-c3bae56b5935.png)|![IMG_6774](https://user-images.githubusercontent.com/94854258/200653794-5e5d9753-16a1-43f3-94d1-05f106a2c11b.png)|![IMG_6773](https://user-images.githubusercontent.com/94854258/200653844-49d85f67-e06c-4caa-8a5e-98212d9321b1.png)|
> [HotFix] 탈퇴하기 기능 및 뷰 구현

- HappyAnding/HappyAnding.xcodeproj/project.pbxproj
- HappyAnding/HappyAnding/Extensions/String+Extension.swift
- HappyAnding/HappyAnding/Views/Components/MyShortcutCardListView.swift
- HappyAnding/HappyAnding/Views/Components/UserCurationListView.swift
- HappyAnding/HappyAnding/Views/SignInViews/WriteNicknameView.swift
- closes #246 
- 특수문자 입력시 중복확인 버튼 disable
- 특수문자 입력시 시작하기 버튼 disable
- 나의 단축어 -> 내가 등록한 단축어 워딩변경
- 나의 큐레이션 -> 내가 등록한 큐레이션 워딩변경
- 특수문자 입력시 중복확인 버튼 disable 영상
https://user-images.githubusercontent.com/91725382/201735084-015fb54d-1c1f-4198-8a5d-27e7a515183d.MP4
- 나의 단축어, 나의 큐레이션 워딩 변경 사항 스크린샷
> [Feat] 특수문자 입력 제한

- HappyAnding/HappyAnding.xcodeproj/project.pbxproj
- HappyAnding/HappyAnding/Model/Keyword.swift
- HappyAnding/HappyAnding/ViewModel/ShortcutsZipViewModel.swift
- HappyAnding/HappyAnding/Views/SearchView.swift
- closes #248
- 컬렉션 생성 ("Keyword")
- fetch 함수 작성 및 적용
화면상의 변경점 없어서 스크린샷 1장과 파이어베이스 캡쳐본 첨부합니다.
> [Feat] 추천 검색어 서버에서 관리

- HappyAnding/HappyAnding.xcodeproj/project.pbxproj
- HappyAnding/HappyAnding/Extensions/Color+Extension.swift
- HappyAnding/HappyAnding/Views/MyPageViews/SettingViews/WithdrawalView.swift
- HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationInfoView.swift
- HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationSetView.swift
- HappyAnding/HappyAnding/Views/WriteShortcutViews/CategoryModalView.swift
- HappyAnding/HappyAnding/Views/WriteShortcutViews/IconModalView.swift
- HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutTagView.swift
- HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutTitleView.swift
- HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutdescriptionView.swift
- closes #254 
Button이 Disable 상태일때, 버튼 컬러 수정하였습니다
|Light Mode|Dark Mode|
|:---:|:---:|
|![Simulator Screen Shot - iPhone 14 - 2022-11-21 at 01 42 31](https://user-images.githubusercontent.com/103024869/202914939-a610917c-bac0-4078-be2b-42ffc0c2e04a.png)|![Simulator Screen Shot - iPhone 14 - 2022-11-21 at 01 42 36](https://user-images.githubusercontent.com/103024869/202914941-e84288be-ec9e-4ac7-ad46-1a032d245803.png)|
> [Feat] #254 - Button Disable Color Change

- HappyAnding/HappyAnding.xcodeproj/project.pbxproj
- HappyAnding/HappyAnding/Views/MyPageViews/SettingView.swift
- HappyAnding/HappyAnding/Views/MyPageViews/SettingViews/WithdrawalView.swift
- HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutView.swift
- HappyAnding/HappyAnding/Views/SignInViews/WriteNicknameView.swift
- closes #260 
- NavigationStack이 수정되고 오류는 없어졌지만 deprecated된 코드들(Alert, windows) 수정했습니다.
- 닉네임 작성 화면에서 중복확인 후 키보드가 내려갔으면 좋겠다는 피드백 반영했습니다 ~!
> [Feat] deprecated Alert 교체

- HappyAnding/HappyAnding.xcodeproj/project.pbxproj
- HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutView.swift
- HappyAnding/HappyAnding/Views/ShortcutDetailViews/UpdateShortcutView.swift
- HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationSetView.swift
- HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutTitleView.swift
- closes #263 
- 단축어 업데이트 화면 (UpdateShortcutView) 생성했습니다.
- 디자이너님께💌 text_button_disable 컬러는 머지되면 수정하신 색으로 적용될 것 같습니다 ~ !
- 풀모달로 뜨는 화면들의 닫기버튼 텍스트는 "취소"로 결정되었습니다 !!!
|light mode|dark mode|
|:---:|:---:|
|![Simulator Screen Shot - iPhone 14 - 2022-11-21 at 17 27 59](https://user-images.githubusercontent.com/76623853/203001990-cfbe6b1a-ba3f-4d77-8f26-d84bae7143ce.png)|![Simulator Screen Shot - iPhone 14 - 2022-11-21 at 17 27 43](https://user-images.githubusercontent.com/76623853/203002026-ebfed1cf-6207-4145-8abd-94975b3a0c41.png)|
> [Feat] 단축어 업데이트화면 UI

- HappyAnding/HappyAnding.xcodeproj/project.pbxproj
- HappyAnding/HappyAnding/ViewModel/NavigationViewModel.swift
- HappyAnding/HappyAnding/Views/ExploreCurationViews/ExploreCurationView.swift
- HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/ExploreShortcutView.swift
- HappyAnding/HappyAnding/Views/MyPageViews/MyPageView.swift
- HappyAnding/HappyAnding/Views/TabView/ShortcutTabView.swift
- HappyAnding/HappyAnding/Views/TabView/TabRouter.swift
- closes #262
- NavigationPath들의 선언 위치가 변경되었습니다.
- NavigationViewModel의 ShortNavigation 안의 변수명을 통일성 위해 변경했습니다.
- 탭라우터를 활용하지 못했습니다 ..ㅎ
- 🚨 루트뷰로 왔을 떄 리로드되면서 깜빡거리는 현상이 있습니다.
> [Feat] 탭뷰 누르면 첫번째 페이지로 이동

- HappyAnding/HappyAnding.xcodeproj/project.pbxproj
- HappyAnding/HappyAnding/Extensions/URL+Extension.swift
- HappyAnding/HappyAnding/Info.plist
- HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutView.swift
- HappyAnding/HappyAnding/Views/TabView/ShortcutTabView.swift
- HappyAnding/HappyAnding/Views/TabView/TabRouter.swift
- #279
- 공유하기
- 딥링크 눌렀을때 링크연결
- 앱이 맨 처음 꺼져있을 때 딥링크 연결하면 한번씩 디테일뷰 빈화면으로 뜰 때 있어서 이 부분 수정해야할 것 같슴다.
- 이 전 PR들에서 탭뷰 관련 변동이 많은 것 같아서 다른 PR 다 합쳐지면 conflict 해결하고 머지할께요
https://user-images.githubusercontent.com/91725382/203057659-c1575b5c-30f3-404b-bf0c-81b233232f42.MP4
https://user-images.githubusercontent.com/91725382/203058434-b407c38b-8217-4f79-92ae-ce3b134052f5.mov
> [Feat] 앱 설치 유저에게 deep link 공유하기

- HappyAnding/HappyAnding/Views/SearchView.swift
- HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutView.swift
- HappyAnding/HappyAnding/Views/WriteShortcutViews/CategoryModalView.swift
- closes #282 
- ReadShortcutView에 stickyheader를 추가했습니다.
- SearchView에서 검색결과가 없을 때 나타나는 단축어 제안 버튼에 동작을 추가했습니다.
- CategoryModalView의 disable 버튼 컬러를 수정했습니다.
|stickyHeader|SearchView|
|:---:|:---:|
|https://user-images.githubusercontent.com/94854258/203265585-8523d146-a4dd-4fbd-ae6c-9af64ad38959.mp4|https://user-images.githubusercontent.com/94854258/203265751-8b2ae566-9d70-411b-b5c0-9cad11bbd3e0.mp4|
> [Feat] stickyheader, button fnction and design change

- HappyAnding/HappyAnding.xcodeproj/project.pbxproj
- HappyAnding/HappyAnding/Extensions/Color+Extension.swift
- HappyAnding/HappyAnding/Views/Components/ListShortcutView.swift
- HappyAnding/HappyAnding/Views/Components/MyShortcutCardListView.swift
- HappyAnding/HappyAnding/Views/Components/ShortcutCardCell.swift
- HappyAnding/HappyAnding/Views/Components/ShortcutCell.swift
- HappyAnding/HappyAnding/Views/ExploreCurationViews/ListCurationView.swift
- HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/CategoryCardView.swift
- HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/ExploreShortcutView.swift
- HappyAnding/HappyAnding/Views/MyPageViews/MyPageView.swift
- HappyAnding/HappyAnding/Views/SearchView.swift
- HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutView.swift
- HappyAnding/HappyAnding/Views/WriteShortcutViews/CategoryModalView.swift
- closes #278 
- 좋아요한 / 다운로드한 단축어 셀 변경
- 리스트 비어있는 경우 ㅇㅇㅇ가 없습니다. 문구 추가
|iPhone 13|iPhone 13|iPhone 13|
|![Simulator Screen Shot - iPhone13 - 2022-11-22 at 17 28 41](https://user-images.githubusercontent.com/41153398/203264808-254afda9-4cd5-47b9-a528-b655241a9c7c.png)|![Simulator Screen Shot - iPhone13 - 2022-11-22 at 17 28 46](https://user-images.githubusercontent.com/41153398/203264823-bbdbc47a-12c2-431f-a2b4-b28fbce7b40a.png)|![Simulator Screen Shot - iPhone13 - 2022-11-22 at 17 29 41](https://user-images.githubusercontent.com/41153398/203264829-0de42a56-59fe-47f8-9473-506e16c974e4.png)|
> [Feat] 마이페이지 디자인 변경

- HappyAnding/HappyAnding.xcodeproj/project.pbxproj
- HappyAnding/HappyAnding/Extensions/Color+Extension.swift
- HappyAnding/HappyAnding/ViewModel/ShortcutsZipViewModel.swift
- HappyAnding/HappyAnding/Views/Components/ListShortcutView.swift
- HappyAnding/HappyAnding/Views/Components/MyShortcutCardListView.swift
- HappyAnding/HappyAnding/Views/Components/ShortcutCardCell.swift
- HappyAnding/HappyAnding/Views/Components/ShortcutCell.swift
- HappyAnding/HappyAnding/Views/ExploreCurationViews/ListCurationView.swift
- HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/CategoryCardView.swift
- HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/ExploreShortcutView.swift
- HappyAnding/HappyAnding/Views/MyPageViews/MyPageView.swift
- HappyAnding/HappyAnding/Views/SearchView.swift
- HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutVersionView.swift
- HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutView.swift
- HappyAnding/HappyAnding/Views/ShortcutDetailViews/UpdateShortcutView.swift
- HappyAnding/HappyAnding/Views/WriteShortcutViews/CategoryModalView.swift
- closes #283
- 단축어 업데이트 시 단축어 정보 변경 (서버, 뷰모델)
- 단축어 업데이트 시 단축어가 포함된 큐레이션 셀정보 변경
화면 상의 변경점이 없어서 생략합니다
> [Feat] 단축어 업데이트 함수 적용

- HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutView.swift
- 선출시 작업을 위한 댓글 화면 제거
|iPhone 13|iPhone 13|iPhone 13|
|![Simulator Screen Shot - iPhone13 - 2022-11-23 at 03 53 18](https://user-images.githubusercontent.com/41153398/203397658-c33cc8a3-7d7f-44f9-a900-1e6908f04da6.png)|![Simulator Screen Shot - iPhone13 - 2022-11-23 at 03 53 20](https://user-images.githubusercontent.com/41153398/203397676-79857110-2348-4297-bd83-9e202ee5c18f.png)|![Simulator Screen Shot - iPhone13 - 2022-11-23 at 03 53 32](https://user-images.githubusercontent.com/41153398/203397680-f4337090-08b0-4d53-8ed6-d5131978b882.png)|
> [Feat] 출시를 위한 댓글 화면 제거

- HappyAnding/HappyAnding/Extensions/View+Extension.swift
- HappyAnding/HappyAnding/Model/Comment.swift
- HappyAnding/HappyAnding/ViewModel/ShortcutsZipViewModel.swift
- HappyAnding/HappyAnding/Views/ExploreCurationViews/ReadAdminCurationView.swift
- HappyAnding/HappyAnding/Views/ExploreCurationViews/ReadUserCurationView.swift
- HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutCommentView.swift
- HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutView.swift
- 댓글 추가
- 답글 추가
- 댓글/답글 삭제 (삭제 시 alert 추가)
- 수정 기능은 미완료한 상태로 주석처리했습니다. 추후 기능 추가하여 한번 더 pr을 올릴 예정입니다.
|iPhone 13|iPhone 13|iPhone 13|
|![Simulator Screen Shot - iPhone13 - 2022-11-23 at 14 30 08](https://user-images.githubusercontent.com/41153398/203476595-39383c67-ff31-42cb-b81a-d3c75ce07481.png)|![Simulator Screen Shot - iPhone13 - 2022-11-23 at 14 31 26](https://user-images.githubusercontent.com/41153398/203476623-9d301f93-330a-4a40-aa6d-a9d086315c89.png)|![Simulator Screen Shot - iPhone13 - 2022-11-23 at 14 37 31](https://user-images.githubusercontent.com/41153398/203476637-c9bfaca2-8f57-4ea1-b681-8446fa3fb908.png)|
|iPhone 13|iPhone 13|iPhone 13|
|![Simulator Screen Shot - iPhone13 - 2022-11-23 at 14 31 …
> [Feat] 댓글 추가, 삭제 기능 추가

- HappyAnding/HappyAnding/ViewModel/ShortcutsZipViewModel.swift
- HappyAnding/HappyAnding/Views/Components/CurationListView.swift
- HappyAnding/HappyAnding/Views/ExploreCurationViews/ExploreCurationView.swift
- HappyAnding/HappyAnding/Views/ExploreCurationViews/ListCurationView.swift
- closes #289 
- 바뀐 UI 적용
- 모음집 로직
https://user-images.githubusercontent.com/91725382/203332458-cf37a027-369b-4b2a-a489-31f59d01630a.MP4
> [Feat] ExploreCurationView 바뀐 UI 적용

- HappyAnding/HappyAnding/Views/SearchView.swift
- closes #294
- 검색어 자동완성 기능 추가
- subtitle로 검색 추가
https://user-images.githubusercontent.com/41153398/203565524-b0d56fa6-eee4-469f-bfd5-3fa03f343f4a.mp4
> [Feat] 검색 기능 업그레이드

- HappyAnding/HappyAnding.xcodeproj/project.pbxproj
- HappyAnding/HappyAnding/Views/MyPageViews/EditNicknameView.swift
- HappyAnding/HappyAnding/Views/MyPageViews/MyPageView.swift
- HappyAnding/HappyAnding/Views/SearchView.swift
- HappyAnding/HappyAnding/Views/SignInViews/WriteNicknameView.swift
- closes #291 
- EditNicknameView UI 생성 및 구현했습니다.
- alert 창 띄우는 시점 조정했습니다.
- @mxnxxii 중복확인 버튼컬러랑 완료 텍스트컬러 등 확인해주세요 ... !
|light mode|dark mode|
|:---:|:---:|
|![Simulator Screen Shot - iPhone 14 - 2022-11-23 at 22 48 46](https://user-images.githubusercontent.com/76623853/203565962-109a718c-d72d-4d75-97ce-60eaaacd138b.png)|![Simulator Screen Shot - iPhone 14 - 2022-11-23 at 22 48 52](https://user-images.githubusercontent.com/76623853/203565995-9bde84f4-d391-4107-bd24-2827cb30cc66.png)|
> [Feat] 닉네임 수정 뷰 구현

- HappyAnding/HappyAnding/Views/ExploreCurationViews/ExploreCurationView.swift
- HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/DownloadRankView.swift
- HappyAnding/HappyAnding/Views/MyPageViews/MyPageView.swift
- HappyAnding/HappyAnding/Views/TabView/ShortcutTabView.swift
- closes #298
- 어제 릴리즈된 버전에서 있었으면 좋겠다고 생각한 기능이라 넣어봤습니다 ~~!
- 탭뷰가 두번 탭되었을 때 뷰의 top으로 스크롤됩니다.
https://user-images.githubusercontent.com/76623853/203727902-b2ddc1f4-e5bc-427f-a6eb-7d0402ec5386.mov
> [Feat] 탭바 두번 탭하면 뷰의 맨 위로 이동

- HappyAnding/HappyAnding/Views/ExploreCurationViews/ListCurationView.swift
- HappyAnding/HappyAnding/Views/ExploreCurationViews/ReadUserCurationView.swift
- HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutView.swift
- HappyAnding/HappyAnding/Views/TabView/ShortcutTabView.swift
- closes #299 
- 유저 큐레이션 딥링크 기능 추가
https://user-images.githubusercontent.com/91725382/203719423-b686b1b9-9ee6-49d4-ac88-59a5896aa4dd.MP4
https://user-images.githubusercontent.com/91725382/203719387-69c71d8d-27d2-4652-81d4-ff5de1951e45.MP4
> [Feat] curation deeplink 기능 추가

- HappyAnding/HappyAnding.xcodeproj/project.pbxproj
- HappyAnding/HappyAnding/Extensions/Font+Extension.swift
- HappyAnding/HappyAnding/Views/Components/CustomTextEditor.swift
- HappyAnding/HappyAnding/Views/Components/ValidationCheckTextField.swift
- HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationInfoView.swift
- HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationSetView.swift
- closes #328
- 디자인 변경사항 구현 완
https://user-images.githubusercontent.com/68676844/204159336-ec293a35-5150-4533-8543-03a6509cee68.mov
- 텍스트 에디터의 경우, axis를 적용할 수 없어 UITextField로 구현하였습니다.
- placeholder를 함께 구현하고자 하였으나, UITextField역시 placeholder가 존재하지 않아 text를 커스텀해야합니다.
- 저희 프로젝트의 경우, Text의 길이로 검사를 진행하여 placeholder를 UITextField에서 구현할 수 없었습니다
- multipleLine의 경우, 이모지를 막는 정규식을 사용하면, 엔터 등의 특수문자도 입력할 수 없어서 해당 부분에는 특수문자 제한을 걸지 않았습니다!
- Figma를 보고 진행하긴 하였으나, 모호한 부분이 있어 영상 잘 참고해주세요 제가 이해한 바는 다음과 같습니다.
- 텍스트필드 클릭 -> 커서만 등장
- 입력 중 (글자가 1개 이상, 조건에 맞을 때) -> 파란색 테두리 + x 버튼
- 입력 중 (조건에 맞지 않을 때) -> 빨간색 테두리 + x 버튼
- 입력 정상 완료 -> 검정색 테두리 + 초록색 체크표시
- 입력 비정상 완료 -> 검정색 테두리 + 빨간색 엑스 표시 : 해당 부분은 디자인이 없어서 임의로 작업했습니다.
> [Feat] 큐레이션 UI 업데이트 및 텍스트필드 업데이트

- HappyAnding/HappyAnding/Model/SectionType.swift
- HappyAnding/HappyAnding/Views/Components/CustomTextEditor.swift
- HappyAnding/HappyAnding/Views/Components/UserCurationListView.swift
- HappyAnding/HappyAnding/Views/Components/ValidationCheckTextField.swift
- HappyAnding/HappyAnding/Views/ExploreCurationViews/ExploreCurationView.swift
- HappyAnding/HappyAnding/Views/ExploreCurationViews/ListCurationView.swift
- HappyAnding/HappyAnding/Views/MyPageViews/MyPageView.swift
- HappyAnding/HappyAnding/Views/MyPageViews/SettingViews/WithdrawalView.swift
- HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutCommentView.swift
- HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutVersionView.swift
- HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutView.swift
- HappyAnding/HappyAnding/Views/TabView/ShortcutTabView.swift
- HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationInfoView.swift
- HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationSetView.swift
- closes #337 
- closes #344 
- validation textfield 수정
- 특수문자 제한 삭제
- 포커스 시 파란색으로 띄우기
- 실패 아이콘 수정
- Write Curation View
- modal "취소"로 변경
- ReadShortcutsView
- 비어있을 때 텍스트 위치 변경
- 워딩 수정
- 큐레이션 -> 추천모음집으로 변경
- 나의 단축어 -> 내가 작성한 단축어로 변경
https://user-images.githubusercontent.com/68676844/205067518-1ef317f3-19a3-49e7-83b9-352fda244522.mov
- 텍스트 에디터의 height이 자동으로 줄어드는 문제는 조건문을 추가하여 해결하였습니다.
- TabView에 minHeight을 지정하는 방식으로 변경
> [Feat] design 업데이트

- HappyAnding/HappyAnding.xcodeproj/project.pbxproj
- HappyAnding/HappyAnding/Views/Components/NicknameTextField.swift
- HappyAnding/HappyAnding/Views/MyPageViews/EditNicknameView.swift
- HappyAnding/HappyAnding/Views/SignInViews/WriteNicknameView.swift
- closes #350 
- 닉네임 뷰 텍스트 필드를 수정하였습니다.
- 재사용 뷰로 구현하였습니다.
https://user-images.githubusercontent.com/68676844/205179220-e31d430d-772e-46af-b0ca-195a7a5ea27c.mov
> Write nick name view/text field

- HappyAnding/HappyAnding.xcodeproj/project.pbxproj
- HappyAnding/HappyAnding/Extensions/View+Navigation.swift
- HappyAnding/HappyAnding/Model/NavigationStackModel.swift
- HappyAnding/HappyAnding/Views/Components/CurationListView.swift
- HappyAnding/HappyAnding/Views/Components/ListShortcutView.swift
- HappyAnding/HappyAnding/Views/Components/MyShortcutCardListView.swift
- HappyAnding/HappyAnding/Views/Components/UserCurationListView.swift
- HappyAnding/HappyAnding/Views/ExploreCurationViews/ExploreCurationView.swift
- HappyAnding/HappyAnding/Views/ExploreCurationViews/ListCurationView.swift
- HappyAnding/HappyAnding/Views/ExploreCurationViews/ReadAdminCurationView.swift
- HappyAnding/HappyAnding/Views/ExploreCurationViews/ReadUserCurationView.swift
- HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/CategoryCardView.swift
- HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/CategoryView.swift
- HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/DownloadRankView.swift
- HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/ExploreShortcutView.swift
- HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/LovedShortcutView.swift
- HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/RecentRegisteredView.swift
- HappyAnding/HappyAnding/Views/ExploreShortcutViews/ListCategoryShortcutView.swift
- HappyAnding/HappyAnding/Views/MyPageViews/MyPageView.swift
- HappyAnding/HappyAnding/Views/MyPageViews/SettingView.swift
- HappyAnding/HappyAnding/Views/SearchView.swift
- HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutHeaderView.swift
- HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutView.swift
- HappyAnding/HappyAnding/Views/ShortcutDetailViews/ShowProfileView.swift
- HappyAnding/HappyAnding/Views/TabView/NavigationRouter.swift
- HappyAnding/HappyAnding/Views/TabView/ShortcutTabView.swift
- HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationSetView.swift
- HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutView.swift
- closes #380
- Navigation Stack에서 발생한 오류입니다. iOS 16에서만 발생합니다. 
- #389 결론으로 Navigation stack과 Navigation view를 분리하여 문제를 해결하였습니다.
1. 이슈
https://user-images.githubusercontent.com/68676844/216615544-9311d58e-22d4-475b-a8b5-e2b48c059898.mov
3. 해결
https://user-images.githubusercontent.com/68676844/220012259-bce1e0e5-a3c4-47fc-b111-fd2bb5ac5560.mov
- 파일이름, 구조체 이름, view builder 함수 이름에 대해 리뷰부탁드립니다.
- 중복 코드를 줄이기 위해 Navigation Router라는 구조체, navigation link router라는 함수를 통해 구현하였으나, 네비게이션 링크라는 것이 직관적으로 보이지 않아 고민이 됩니다. 조언 부탁드려요!
- 저희 Navigation Stack 적용했을 때 처럼 꼼꼼한 테스트가 필요합니다. (iOS 16, iOS 16이후 버전 둘 다 테스트 부탁드립니다)
> [Fix] #380 - swipe back 이슈 해결

- HappyAnding/HappyAnding.xcodeproj/project.pbxproj
- HappyAnding/HappyAnding/Extensions/Color+Extension.swift
- HappyAnding/HappyAnding/ViewModel/WriteShortcutModalViewModel.swift
- HappyAnding/HappyAnding/ViewModel/WriteShortcutViewModel.swift
- HappyAnding/HappyAnding/Views/Components/MyShortcutCardListView.swift
- HappyAnding/HappyAnding/Views/ReadShortcutViews/ReadShortcutView.swift
- HappyAnding/HappyAnding/Views/WriteShortcutViews/CategoryModalView.swift
- HappyAnding/HappyAnding/Views/WriteShortcutViews/IconModalView.swift
- HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutView.swift
- HappyAnding/ShareExtension/ShareExtensionWriteShortcutView.swift
- closes #475 
- writeShortcutViewModel적용
- 모달 창의 경우 양방향 데이터 전달이 필요해 viewModel을 거의 활용하지 못했습니다.
화면상의 변경사항 없음
> [Feat] write shortcut view model 적용

- HappyAnding/HappyAnding.xcodeproj/project.pbxproj
- HappyAnding/HappyAnding/Views/ReadShortcutViews/ReadShortcutView.swift
- closes #455 
- 외부링크 hyper text 적용
- 줄글 잘리는 이슈로 Spacer()의 프레임 지정 삭제
|iPhone SE(색상 변경 전)|iPhone 13(색상 변경 전)|iPhone 14 Pro Max (색상 변경 후)|
|![Simulator Screenshot - iPhone SE (3rd generation) - 2023-08-28 at 22 59 47](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-HappyAnding/assets/41153398/de44ce7a-4230-4dfb-8785-c8ffde261dd5)|![IMG_427620EC9E1D-1](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-HappyAnding/assets/41153398/bc73525f-df12-4c39-9161-fdf185511a52)| ![Simulator Screenshot - iPhone 14 Pro Max - 2023-08-29 at 00 08 45](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-HappyAnding/assets/41153398/51ff38ce-709b-4882-9c32-9b2c814df41c) |
별다른 설정없이 .init을 추가한 것 만으로 hyper text가 적용이 되는 이유는 
attribute style을 적용시키는 initializer이기 때문이라고 추측됩니다. 
사용예시 1 …
> [Feat] hyperText 적용

- HappyAnding/HappyAnding.xcodeproj/project.pbxproj
- HappyAnding/HappyAnding/Assets.xcassets/Colors/CharcoalGray.colorset/Contents.json
- HappyAnding/HappyAnding/Extensions/View/View+Shadow.swift
- HappyAnding/HappyAnding/Extensions/View/View+Shape.swift
- closes #521
- roundedBorder extension을 제작했습니다.
- view 가장자리에 지정된 round 및 윤곽선 효과를 적용합니다.
- 3가지의 매개변수가 존재합니다. (기본값 사용 가능)
- `cornerRadius: 둥근 모서리의 정도를 설정합니다. 기본값 16`
- `color: 테두리의 색상을 설정합니다. 기본값 "CharcoalGray"`
- `opacity: 테두리의 투명도를 설정합니다. 기본값 1.0`
- dropShadow extension을 제작했습니다.
- view 가장자리에 지정된 shadow 효과를 적용합니다.
- 매개변수 없이 바로 사용 가능합니다.
- extension에서의 사용을 위해 asset에 CharcoalGray 색상을 새로 추가했습니다. 추후 변경이 필요합니다.
- 빌드 시 표시되는 ShareExtension의 Firebase Messaging 관련 오류를 해결했습니다.
- 나뉘어 표시되었던 Support 그룹(폴더)을 하나로 통합했습니다.
> [Feat] 공통 Extension 제작 등
