HappyAnding/HappyAnding/Views/WriteShortcutViews/CategoryModalView.swift

- closes #28 
- selectedCategories 배열에 선택된 버튼의 enum case들을 넣어 전달합니다. 
- 완료버튼은 .borderedProminent로 설정해서 높이가 하이파이와 약간 달라보이는데 이후에 다른뷰들과 통일하겠습니다.
|![Simulator Screen Shot - iPhone SE (3rd generation) - 2022-10-24 at 23 46 21](https://user-images.githubusercontent.com/76623853/197559734-da2a42a2-fd8d-4e80-9040-acaca85c9f00.png)|![Simulator Screen Shot - iPhone 14 - 2022-10-24 at 23 44 39](https://user-images.githubusercontent.com/76623853/197559763-287998a2-8c8e-4151-9342-2471ae749489.png)|![Simulator Screen Shot - iPhone 14 Pro Max - 2022-10-24 at 23 45 53](https://user-images.githubusercontent.com/76623853/197559677-bacc727f-99b8-47d4-9a1d-359e6f630b10.png)|

[Feat] CategoryModalView UI

---

HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutTagView.swift

- closes #26 
- 단축어 관련 태그를 가로 스크롤뷰로 구현합니다.
- 카테고리 추가 버튼을 누르면 CategoryModalView가 연결되어야 합니다.
- 앱 추가 버튼을 누르면 텍스트필드가 열리고 return시 태그로 추가됩니다.
- 데이터 구조가 정해지고 Category를 String 배열로 저장하면 코드가 줄어들 수 있습니다.
https://user-images.githubusercontent.com/76623853/197698458-ee8003ba-8f49-4b0e-82b4-5129adfce6c7.mp4

[Feat] WriteShortcutTagView내 Tag 구현

---

HappyAnding/HappyAnding/Views/Components/ListShortcutView.swift

- closes #79
- 패딩 값 구현
- 패딩이서어 iPhone Pro max만 스샷 찍었어요

[Feat] 리스트 맨 마지막에 패딩 44 설정

---

HappyAnding/HappyAnding/Views/Launch Screen.storyboard

- closes #121
- Splash 화면 수정
라이트모드와 다크모드 컬러 동일해서 1개만 첨부합니다
|iPhone 14|
|:---:|
|![Simulator Screen Shot - iPhone 14 - 2022-11-02 at 17 52 46](https://user-images.githubusercontent.com/103024869/199445324-6645251d-0b5d-4998-8bfc-6ed79a6be2d9.png)|

[Feat] #121 - Splash 화면 수정

---

HappyAnding/HappyAnding/Views/Components/ShortcutCell.swift

- closes #54
- shortcut cell 패딩 값 수정
|before|after|
|---|---|
|<img src =  "https://user-images.githubusercontent.com/68676844/199604005-2bf61557-06da-4e29-a460-d682084a5247.png" width = 250>|<img src = "https://user-images.githubusercontent.com/68676844/199603889-9aefe7ae-8265-48f7-90c3-ab5cc9611ae0.png" width = 250>|
- 저는 어떤 차이가 있는지 잘 모르겠어요.. ^^
- 그래도 눈에 자가 달린 로미와 로겐은, 알아차릴 수 있을 거라 믿습니다.

[Feat] 단축어 cell 패딩 값 수정

---

HappyAnding/HappyAnding/Views/Components/ValidationCheckTextField.swift
HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationInfoView.swift
HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutTagView.swift
HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutTitleView.swift
HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutdescriptionView.swift

- closes #113
- 링크가 https://www.icloud.com/shortcuts/으로 시작하는지 확인하여 간단한 유효성 검사를 합니다 
https://user-images.githubusercontent.com/68676844/199614657-79ce9a65-0480-4a80-be80-50eb40063a5a.mp4
- 1차원적으로만 생각한 로직이어서, 검증 부탁드려요

[Feat] 단축어 링크 유효성 검사

---

HappyAnding/HappyAnding/Model/FirebaseService.swift
HappyAnding/HappyAnding/Views/SignInViews/AppleAuthCoordinator.swift
HappyAnding/HappyAnding/Views/SignInViews/UserAuth.swift
HappyAnding/HappyAnding/Views/SignInViews/WriteNicknameView.swift

- closes #145
- closes #151
- 회원가입 뷰 로그인하는 경우는 닉네임 설정 뷰 안 나오도록 구현
- 닉네임 중복확인 후 변경되면, 다시 중복확인 요구하도록 구현
1. 회원가입 -> 닉네임 중복확인 -> 앱종료 후 재접속(자동로그인)
https://user-images.githubusercontent.com/68676844/199710104-ae0168fd-1a6e-487b-b123-e2fe4fff2771.mov
2. 앱 삭제 후 다시 빌드 -> 로그인 -> 닉네임화면 없이 메인화면으로 접속
https://user-images.githubusercontent.com/68676844/199710144-7a53514a-d634-4309-993b-c4b5fd9957ff.mp4
3. 닉네임 중복확인기능 구현
https://user-images.githubusercontent.com/68676844/199711935-afb9647d-1e49-48b8-9c0a-fd05515362f9.mp4
- 엘리 PR 머지되면 머지할게요

회원가입 관련 이슈 해결

---

HappyAnding/HappyAnding/Views/Components/MyShortcutCardListView.swift
HappyAnding/HappyAnding/Views/ExploreCurationViews/ExploreCurationView.swift
HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/ExploreShortcutView.swift
HappyAnding/HappyAnding/Views/MyPageViews/MyPageView.swift
HappyAnding/HappyAnding/Views/WriteShortcutViews/CategoryModalView.swift
HappyAnding/HappyAnding/Views/WriteShortcutViews/IconModalView.swift
HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutTagView.swift
HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutTitleView.swift
HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutdescriptionView.swift

- closes #152 
- 글쓰기 뷰들의 배경색상을 .background로 통일함
- 멀티라인 텍스트 에디터의 zstack으로 쌓인 textfiled 부분이 터치되지 않고, 색이 다르게 표시되던 문제를 해결함
- 단축어 탭과 프로필 탭의 타이틀이 .inline으로 보이던 문제를 해결함
- 프로필 탭에 맞춰 단축어와 큐레이션 탭의 scroll indicator를 보이지 않게 처리함
*색상 변화 인지를 위해 다크모드로 설정 후 스크린샷을 촬영함
|배경색상|텍스트 에디터|타이틀|
|<img width="329" alt="Screenshot 2022-11-04 at 3 25 53" src="https://user-images.githubusercontent.com/94854258/199805179-1455596c-e650-489d-8981-bdef6793f1fa.png">|<img width="318" alt="Screenshot 2022-11-04 at 3 25 38" src="https://user-images.githubusercontent.com/94854258/199805233-218bc7dc-9e22-43b8-b6a9-cb7bc22736f6.png">|<img width="328" alt="Screenshot 2022-11-04 at 3 26 03" src="https://user-images.githubusercontent.com/94854258/199805267-39d28db7-c190-49de-9e35-25ce7d4f6a87.png">|

[Feat] Design Minor Changes 2

---

HappyAnding/HappyAnding/Model/FirebaseService.swift
HappyAnding/HappyAnding/Model/Shortcuts.swift
HappyAnding/HappyAnding/Model/User.swift
HappyAnding/HappyAnding/Views/Components/ShortcutCell.swift
HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutHeaderView.swift
HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutView.swift
HappyAnding/HappyAnding/Views/SignInViews/WriteNicknameView.swift
HappyAnding/HappyAnding/Views/WriteCurationViews/CheckBoxShortcutCell.swift
HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationInfoView.swift
HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationSetView.swift
HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutTagView.swift
HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutTitleView.swift
HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutdescriptionView.swift

- closes #167
- 다운로드 수 업데이트하는 함수 구현 (updateNumberOfDownload)
- 좋아요 수 업데이트하는 함수 구현 (updateNumberOfLike)
- ReadShortcutView에서 현재 사용자가 해당 단축어에 좋아요를 눌렀었는지 판단하는 함수 구현 (checkLikedShortrcut)
- 단축어 수정 시 큐레이션 업데이트하는 함수 (updateShortcutInCuration)
- --> 📌단축어 셀 정보에 포함되는 정보가 변경되었을 때만 사용
- 큐레이션 생성 시 단축어에 id저장하는 함수 (updateShortcutCurationID)
- 단축어 삭제 시 유저 정보에 포함된 id 삭제하는 함수 (deleteShortcutIDInUser)
- 단축어 삭제 시 해당 단축어를 포함하는 큐레이션에서 삭제하는 함수 (deleteShortcutInCuration)
- 큐레이션 삭제 시 단축어에서 id를 삭제하는 함수 (deleteCurationIDInShortcut)
|iPhone 13|iPhone 14|iPhone 14 Pro Max|
|![Simulator Screen Shot - iPhone13 - 2022-11-04 at 08 08 21](https://user-images.githubusercontent.com/41153398/199851976-de92fbdd-dff7-4749-baad-4ee2792b4f8c.png)|pic2|pic3|
- 화면 상의 변경점은 없어 기기별 스크린샷은 생략
- 나갔다 들어와도 좋아요 유지됨
- …

[Feat] 수정 / 삭제 함수 기능 구현

---

HappyAnding/HappyAnding/Views/ExploreCurationViews/ReadUserCurationView.swift
HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutView.swift

- closes #171 
- 단축어 상세 뷰에서 "신고" 버튼 숨기기
- UserCurationView에서 "공유" 버튼 숨기기
- 2차 스프린트 이후 신고 및 공유 기능이 적용될 경우 주석만 삭제하면 버튼 형태를 그대로 사용할 수 있습니다.
|신고버튼 숨기기|공유버튼 숨기기-내 큐레이션|공유버튼 숨기기-유저 큐레이션|
|<img width="335" alt="Screenshot 2022-11-04 at 9 22 12" src="https://user-images.githubusercontent.com/94854258/199859259-885778f4-561f-445f-90ea-d354af55e967.png">|<img width="329" alt="Screenshot 2022-11-04 at 9 22 32" src="https://user-images.githubusercontent.com/94854258/199859279-9e542184-5980-4bb3-866b-aa55ee95c2ba.png">|<img width="335" alt="Screenshot 2022-11-04 at 9 22 47" src="https://user-images.githubusercontent.com/94854258/199859320-7b3ac65f-1b8a-4c9f-929d-d9c4e2668a77.png">|

[Feat] Hide imcomplete functions (공유 및 신고버튼)

---

HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutContentView.swift

- closes #178 
- ReadShortcutView의 컨텐츠 중 값이 없을 수 있는 관련 앱과 요구사항의 경우 값이 없을 때는 해더도 표시되지 않도록 UI 수정
- ReadShortcutView 안 ReadShortcutContentView의 scroll indicator를 보이지 않게 처리
- @JIWON1923 쏘이의 #177 PR 시점의 코드를 풀 받아 작업했습니다.
- 해당 브랜치 머지 이후 머지가 진행되어야 문제가 없을 듯 합니다.
|옵셔널 값들| 스크롤 인디케이터|
|:---:|:---:|
|<img width="326" alt="Screenshot 2022-11-04 at 7 28 04" src="https://user-images.githubusercontent.com/94854258/199846429-6e0190f4-36e2-44a8-ac1f-8ed14c027f51.png">|![Simulator Screen Shot - iPhone 14 - 2022-11-04 at 07 28 17](https://user-images.githubusercontent.com/94854258/199846459-ddb44f00-cfac-413b-835c-7ca5c799d813.png)|

Feat] ReadShortcutView 디자인 수정사항

---

HappyAnding/HappyAnding.xcodeproj/project.pbxproj
HappyAnding/HappyAnding/HappyAnding.entitlements
HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/ExploreShortcutView.swift
HappyAnding/HappyAnding/Views/SearchView.swift

- closes #235 
- 검색 관련 화면 UI
- ExploreShortcutView 탐색버튼
- 서치뷰
- 서치 결과 뷰 ( 결과 있을 때, 없을 때) 
|proposeView|SearchView|ExploreShortcutView 탐색버튼|
|![IMG_4335](https://user-images.githubusercontent.com/91725382/201450378-779c218a-c31e-4bb8-87cc-46e3f749b556.PNG)|![IMG_4334](https://user-images.githubusercontent.com/91725382/201450385-fccfd4f3-ce3f-44f5-bc18-f14b54b5fd22.PNG)|![IMG_4333](https://user-images.githubusercontent.com/91725382/201450393-30076854-88bc-48f5-9c6f-ca0202bdc53b.PNG)|

[Feat] Search view/UI

---

HappyAnding/HappyAnding/ViewModel/ShortcutsZipViewModel.swift
HappyAnding/HappyAnding/Views/Components/ShortcutCell.swift
HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutVersionView.swift
HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutView.swift

- closes #295 
- 이전버전 다운로드 클릭 시 다운로드 숫자 업데이트
- 최신버전 다운로드 클릭 시 현재 가지고 있는 링크와 비교 후 다르면 유저정보 업데이트
- 로그아웃 시 유저가 다운로드한 단축어, 유저가 좋아요한 단축어를 추가적으로 초기화하도록 했습니다.
https://user-images.githubusercontent.com/41153398/203975728-aaa9c069-398d-4e6a-b443-aeaae99877d2.mov

[Feat] 다운로드 버튼 기능 업데이트

---

HappyAnding/HappyAnding/Extensions/Navigationbar+Extension.swift
HappyAnding/HappyAnding/Views/Components/ListShortcutView.swift
HappyAnding/HappyAnding/Views/ExploreCurationViews/ListCurationView.swift
HappyAnding/HappyAnding/Views/ExploreCurationViews/ReadAdminCurationView.swift
HappyAnding/HappyAnding/Views/ExploreCurationViews/ReadUserCurationView.swift
HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/ExploreShortcutView.swift
HappyAnding/HappyAnding/Views/ExploreShortcutViews/ShortcutsListView.swift
HappyAnding/HappyAnding/Views/SearchView.swift
HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutCommentView.swift
HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutView.swift
HappyAnding/HappyAnding/Views/TabView/ShortcutTabView.swift

- closes #288
- closes #302   
- 네비게이션바 백버튼 위치 통일을 위해 툴바를 사용하던 부분을 모두 네비게이션바로 변경
- 네비게이션바 색상을 화면별로 다르게 지정하기 위해 투명으로 지정 및 네비게이션바 영역까지 지정한 색으로 레이어를 하나 더 깔았습니다.
- 댓글 수정, 삭제 버튼이 댓글 작성자일 경우에만 보이도록 수정
- 댓글 수정 기능 추가
- 댓글 수정 시 키보드 포커스
- 댓글 수정 중 스크롤 불가능
- 댓글 수정 취소 시 (텍스트 필드 제외한 영역 터치 시) alert띄움
##To Reviewer
- 네비게이션 바 색상이 스크롤 시 Color.White로 지정되어 기존에 Color.Background로 지정되어있을 때와 약간 차이가 있습니다. 의도된 것이니 감안하고 확인해주세요! 
- 댓글 수정 시 키보드 포커스 반응이 약간 느린듯 보이는데 반응속도를 현재보다 더 빠르게 지정할 경우 아예 반응하지 않아서 이것이 최선입니다..
https://user-images.githubusercontent.com/41153398/204050949-c31cf2ef-0b93-4468-b14e-f9ea6ca4e888.MP4

[Feat] 댓글 수정 + 네비게이션바 버튼 통일

---

HappyAnding/HappyAnding/ViewModel/ShortcutsZipViewModel.swift
HappyAnding/HappyAnding/Views/HappyAndingApp.swift
HappyAnding/HappyAnding/Views/MyPageViews/SettingView.swift
HappyAnding/HappyAnding/Views/MyPageViews/SettingViews/WithdrawalView.swift
HappyAnding/HappyAnding/Views/SignInViews/AppleAuthCoordinator.swift
HappyAnding/HappyAnding/Views/SignInViews/SignInWithAppleView.swift

- closes #231
- 회원탈퇴 과정 중 사용자 재인증 (로그인) 과정 추가
- 기존의 로그인과 재인증 로그인을 구분하는 변수 추가
- 기존에 회원탈퇴 버튼을 눌러도 아무런 반응이 없던 문제는 로그인을 하고 5분이상 지났을 경우에 재인증이 필요해서 발생한 문제로 탈퇴 과정 중 재인증 과정을 넣어 해결했습니다.
- 파이어베이스에서 제공해주는 정석?적인 재인증 과정을 찾지 못해 임의로 사용자를 로그아웃 시키고 다시 로그인 시켜서 해결했습니다.
- 사용자 정보가 삭제가 되지 않던 오류는 파이어베이스에 설정된 규칙 중 인증 된 사용자만 읽기, 쓰기가 가능하도록 설정이 되어있는데 이전 회원탈퇴 과정은 사용자 정보 삭제 전 인증 정보가 먼저 삭제되어 인증되지 않은 사용자 상태로 삭제를 시도하여 발생한 문제로 확인되어 사용자 정보 삭제 후 인증 정보를 삭제하도록 순서를 변경하여 해결했습니다.
- 오류 해결 중간에 공유했던 재인증 과정 중 인증을 하지 않고 창을 닫을 경우에 사용자가 로그아웃되어 로그인화면이 나오던 문제는 재인증을 로그아웃 - 로그인 순서로 하던 것을 로그인만 하도록 변경하여 사용자가 로그아웃되지 않도록 변경하여 해결했습니다.
- 정상적으로 회원탈퇴 과정을 밟는 경우
https://user-images.githubusercontent.com/41153398/204091403-15f7bdca-9cbb-4d51-99d2-442608e72a33.MP4
- 회원탈퇴 재인증 과정 중 인증하지 않고 창을 닫는 경우 (기존에는 인증 과정 중 창을 닫으면 로그아웃되어 앱을 껐다켜면 회원정보를 받아오지 못함) …

[Fix] 회원탈퇴 에러

---

HappyAnding/HappyAnding/Views/MyPageViews/SettingView.swift
HappyAnding/HappyAnding/Views/MyPageViews/SettingViews/LicenseView.swift
HappyAnding/HappyAnding/Views/SignInViews/PrivacyPolicyView.swift
HappyAnding/HappyAnding/Views/SignInViews/WriteNicknameView.swift
HappyAnding/HappyAnding/Views/WriteShortcutViews/CategoryModalView.swift
HappyAnding/HappyAnding/Views/WriteShortcutViews/IconModalView.swift
HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutTagView.swift
HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutTitleView.swift

- closes #303 
- HIG 준수를 위해 핸들 및 닫기 버튼을 추가하였습니다.
|아이콘 선택|카테고리|개인정보처리방침|
|<img src ="https://user-images.githubusercontent.com/68676844/204090635-8d8589d4-0921-4cb3-9128-3e2993ae4718.png" width = 250>|<img src = "https://user-images.githubusercontent.com/68676844/204090647-45fcde96-dedb-4562-95d9-eb75ae3912f6.png" width = 250>|<img src = "https://user-images.githubusercontent.com/68676844/204090665-9d0cdb50-6fc0-42c3-89e5-fc06ca05c6e0.png" width = 250>|
- handle의 경우, iOS 16.0부터 적용가능한 방법입니다.
- 타 버전의 경우 capsule을 ZStack으로 쌓아서 사용하더라고요! 추후 개발시 참고하세요~
```
.presentationDetents([.large])
.presentationDragIndicator(.visible)
```
- 네비게이션 타이틀을 사용해서 닫기 버튼 및 "아이콘" 등의 타이틀을 설정하고 싶었는데, 이를 위해서 네비게이션 타이틀의 높이를 조정하는 코드가 필요했습니다 -> 네비게이션을 커스텀하는 것보다, HStack으로 조정하는 것이 경제적이라고 생각했습니다!
- …

[Feat] 모달에 핸들 및 닫기 버튼 추가

---

HappyAnding/HappyAnding.xcodeproj/project.pbxproj
HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutView.swift

- closes #314
- 다운로드 버튼 클릭 시 실행되는 함수들의 순서를 변경했습니다.
- 서버/뷰모델을 업데이트 함수 -> UI 업데이트 순서에서 UI 업데이트 -> 서버/뷰모델 업데이트 함수 순서로 변경
- 단축어 상세 뷰에서 클릭 시
https://user-images.githubusercontent.com/41153398/204102257-a5c4d5f6-c9bb-4084-83ca-5ad3017b8e32.mp4
- 단축어 셀에서 클릭 시
https://user-images.githubusercontent.com/41153398/204102345-d65b26ed-4406-4a96-92b1-a771f0003ed9.mp4

[Fix] 단축어 다운로드 숫자 업데이트

---

HappyAnding/HappyAnding/ViewModel/ShortcutsZipViewModel.swift
HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationInfoView.swift
HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationSetView.swift

- closes #316
- 큐레이션 편집에서 단축어 제거 시 단축어 정보에서 curation id 지우는 기능 추가
https://user-images.githubusercontent.com/41153398/204107571-fa3f81a5-21e8-4517-945f-07a9d2bbd81f.mov

[Feat] 큐레이션 편집에서 단축어 제거 시 단축어의 큐레이션 아이디 제거하는 함수 추가

---

HappyAnding/HappyAnding/ViewModel/ShortcutsZipViewModel.swift

- 유저 정보가 없을 경우 로그인 페이지로 연결하도록 처리
- closes #313 
- 여러 기기에서 사용 시 한 곳에서 탈퇴 시 다른 기기에서 유저 정보가 없는 상태로 앱에 남아있는 경우가 존재했음 
- 유저정보를 받아오는 도중 빈배열을 받아오는 경우 signInStatus를 변경하여 로그인페이지로 연결되도록 변경
https://user-images.githubusercontent.com/41153398/204137187-54bc5eee-c646-43c1-b6be-0782ac447295.mov

[Fix] 유저 정보가 없을 경우 처리

---

HappyAnding/HappyAnding/Views/Components/ValidationCheckTextField.swift
HappyAnding/HappyAnding/Views/MyPageViews/EditNicknameView.swift
HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutHeaderView.swift
HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutView.swift
HappyAnding/HappyAnding/Views/SignInViews/WriteNicknameView.swift
HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutTagView.swift

- closes #322
- closes #320 
- 서브타이틀 ...로 표기되는 것 수정
- 텍스트필드 자동수정 막기 (자동 수정 및 첫글자 대문자로 바뀌는 것 수정)
|<img src = "https://user-images.githubusercontent.com/68676844/204133365-af6da0bb-9cf2-476e-890e-38528a9ee38f.png" width = 250>|<img src = "https://user-images.githubusercontent.com/68676844/204133018-94fe3e38-c5e2-4157-8bfb-b1496cdc6106.png" width = 250>|<img src = "https://user-images.githubusercontent.com/68676844/204133421-c7d98a0c-5778-47b9-bda1-9968f9cc6948.png" width = 250>

[Feat] 서브타이틀 줄임표 없애기, 자동완성 막기

---

HappyAnding/HappyAnding/Model/NavigationStackModel.swift
HappyAnding/HappyAnding/ViewModel/ShortcutsZipViewModel.swift
HappyAnding/HappyAnding/Views/Components/CurationListView.swift
HappyAnding/HappyAnding/Views/Components/ListShortcutView.swift
HappyAnding/HappyAnding/Views/Components/MyShortcutCardListView.swift
HappyAnding/HappyAnding/Views/Components/UserCurationListView.swift
HappyAnding/HappyAnding/Views/ExploreCurationViews/ExploreCurationView.swift
HappyAnding/HappyAnding/Views/ExploreCurationViews/ListCurationView.swift
HappyAnding/HappyAnding/Views/ExploreCurationViews/ReadAdminCurationView.swift
HappyAnding/HappyAnding/Views/ExploreCurationViews/ReadUserCurationView.swift
HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/CategoryCardView.swift
HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/CategoryView.swift
HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/DownloadRankView.swift
HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/ExploreShortcutView.swift
HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/LovedShortcutView.swift
HappyAnding/HappyAnding/Views/ExploreShortcutViews/ShortcutsListView.swift
HappyAnding/HappyAnding/Views/MyPageViews/MyPageView.swift
HappyAnding/HappyAnding/Views/SearchView.swift
HappyAnding/HappyAnding/Views/TabView/ShortcutTabView.swift

- closes #306 
- closes #310 
- NavigationListCurationType 수정
- ListView 에서 2개의 미리보기 목록 및 타이틀과 헤더가 Struct로 분리되어있어 불필요한 요청을 많이 발생하는 것 같아 하나의 구조체 내에서 분리했습니다. (binding, onChange 코드의 중복을 제거하기 위해서)
- 네비게이션 관련 콘솔이 지속적으로 출력되는 문제를 해결했습니다.
- 큐레이션 모아보기 등 사라졌던 네비게이션 타이틀을 복구했습니다.
- 브랜치에 이상이 있어 이름 수정하여 다시 PR 올립니다. 
- 다운로드한 단축어가 없을 때, 단축어 모아보기에 아무것도 출력되지 않던 문제 해결
- 뷰 변경은 존재하지 않아 동영상 녹화로 대체합니다!
https://user-images.githubusercontent.com/68676844/204099733-2fc205b1-f31e-4014-9b18-128fdf459ace.mov
- 현재 다운로드 받지 않은 단축어도 ~를 위한 모음집에 뜨는 이유는 큐레이션 편집했을 때, 단축어 정보가 삭제 되어도, 해당 큐레이션 내 단축어 id 정보가 삭제되지 않아서입니다! 해당 작업은 이슈 끊어놨으니 선착순으로 가져가세요!
- 네비게이션 스택의 로그가 발생한 경우는 하나의 네비게이션 스택에서 같은 데이터를 참조했기 때문입니다.
- 탭바 선언된 부분에 데스티네이션을 선언하여 문제를 해결했습니다.
- 단축어 모아보기에 아무것도 출력되지 않던 문제의 경우, 네비게이션 스택 데이터 전달에 이슈가 있었기 때문입니다!
- 기존 바인딩으로 넘겼던 큐레이션 …

[Fix] 큐레이션 모아보기 에러 수정 및 네비게이션 스택 리팩토링

---

HappyAnding/HappyAnding/Views/SearchView.swift

- closes #330
- 검색하는 단어만 소문자로 처리되어 발생한 이슈였습니다!
- 저장되어있는 데이터도 소문자로 변경하여 해당 이슈 해결했습니다.
https://user-images.githubusercontent.com/68676844/204160864-528911b7-8125-4b27-8918-e54315464707.mov

[Fix] 영어 검색 안되는 이슈 해결

---

HappyAnding/HappyAnding/Views/ExploreCurationViews/ReadUserCurationView.swift

- closes #315 
- 큐레이션 편집에서 단축어 선택 해제 시 ReadCurationView에 정보가 다르게 업데이트 되는 현상 해결
- 기존 array.enumerated()를 이용하여 ForEach 문을 사용하였던 부분을 array로 변경하여 ForEach을 사용
- 기존에 enumerated를 사용한 이유는 마지막 인덱스일 때 padding을 다르게 넣기 위함이었는데 이를 ForEach문이 끝난 후에 넣어주는 것으로 해결
https://user-images.githubusercontent.com/41153398/204151895-32d4ced2-7b91-4398-91e3-773c44b07a45.mp4

[Fix] 큐레이션 단축어 셀 리스트 업데이트 에러

---

HappyAnding/HappyAnding.xcodeproj/project.pbxproj
HappyAnding/HappyAnding/Extensions/Image+Extension.swift
HappyAnding/HappyAnding/Views/Components/ListShortcutView.swift
HappyAnding/HappyAnding/Views/Components/ShortcutCell.swift

- closes #327 
- ListShortcutView에서 ShortcutCell로 sectionType을 전달하도록 함
- ShortcutCell의 downloadInfo에서 sectionType이 myDownloadShortcut인 경우 유저 정보에 등록된 다운로드 링크와 단축어의 최신 링크를 비교하여 다를 경우 업데이트를 나타내는 아이콘을 띄우로도록 함
https://user-images.githubusercontent.com/41153398/204142625-f55d00df-785b-4519-b70f-4ec0c07e62bd.mp4

[Feat] 다운로드한 단축어 셀 업데이트 아이콘 표시

---

HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutView.swift

- closes #333
- 제목이 길어졌을 때, 뷰가 잘리는 이슈 해결
- Frame이지정되어있어서 발생한 문제입니다.
- minHeight으로 바꿔서 해결했습니다
|<img src = "https://user-images.githubusercontent.com/68676844/204277338-7d888bc4-da6d-4472-bed4-360b178430b7.png" width = 250>|<img src = "https://user-images.githubusercontent.com/68676844/204277305-69d5d3c7-ef70-4ce3-9fd3-1d68068bd059.png" width = 250>|<img src = "https://user-images.githubusercontent.com/68676844/204277629-7585e4f9-fd06-447f-a682-48093dd4d9b3.png" width = 250>|

[Fix] 단축어 read view 뷰 밀리는 문제 해결

---

HappyAnding/HappyAnding.xcodeproj/project.pbxproj
HappyAnding/HappyAnding/Info.plist
HappyAnding/HappyAnding/Views/TabView/ShortcutTabView.swift
HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutTitleView.swift

- closes #342
- 3개 페이지로 나뉘어져 있던 WriteCurationView를 하나로 통합했습니다.
- 카테고리 선택 버튼의 UI를 변경했습니다.
- 단축어 사용에 필요한 앱에 대한 설명을 추가했습니다.
- 이 외 작은 UI 변경사항 반영 및 수정이 있습니다.
- 통합되어 사용되지 않는 2개의 파일(WriteShortcutdescriptionView, WriteShortcutTagView)는 코드리뷰 후, 머지 전에 삭제 예정입니다.
- NavigationStack 관련 필요 없는 코드가 남아있는지 봐 주시면 감사하겠습니다!
- 더 이상 사용되지 않는 단축어 사용을 위한 요구사항 관련해 추가적으로 처리할 부분은 없는지 확인해주시면 감사하겠습니다. 
- 업로드 버튼의 컬러 확인 부탁드립니다. @mxnxxii 
작동 시 동영상 파일로 대체합니다.
https://user-images.githubusercontent.com/94854258/205138097-e04cd211-861f-41d2-8091-8e4c5d96708c.mp4

Write Curation View UI 변경사항

---

HappyAnding/HappyAnding/Views/SearchView.swift

- closes #345 
- 서치바 플레이스홀더 텍스트 변경
- 검색결과 없을 때 검색한 단어 앞뒤로 쌍따옴표 추가
https://user-images.githubusercontent.com/91725382/204996884-8e4d7b52-58ee-47f9-8598-cb2b7891eb46.MP4

[feat] Searchable UI 변경

---

HappyAnding/HappyAnding.xcodeproj/project.pbxproj
HappyAnding/HappyAnding/Model/NavigationStackModel.swift
HappyAnding/HappyAnding/Model/User.swift
HappyAnding/HappyAnding/Views/Components/ShortcutCell.swift
HappyAnding/HappyAnding/Views/ExploreCurationViews/ReadUserCurationView.swift
HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/CategoryCardView.swift
HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/CategoryView.swift
HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/DownloadRankView.swift
HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/LovedShortcutView.swift
HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutHeaderView.swift
HappyAnding/HappyAnding/Views/ShortcutDetailViews/ShowProfileView.swift
HappyAnding/HappyAnding/Views/TabView/ShortcutTabView.swift

- closes #308 
- 단축어 상세 화면, 큐레이션 상세 화면에서 닉네임 클릭시 넘어가는 프로필 화면을 구현했습니다.
- CurationCell은 bottom에 패딩이 있고, ShortcutCell은 top에 패딩이 있어서 bottom padding으로 통일했습니다.
- 큐레이션에 관한 워딩은 수정될 예정입니다.
- 등록한 컨텐츠가 없는 경우 임의의 텍스트를 표시했는데 디자인 및 워딩 수정이 필요하다면 말씀해주세요.
- 사용자 정보가 없는 경우 닉네임이 "닉네임"이라고 표시되었는데 이를 "탈퇴한 사용자"로 변경하고 프로필 화면으로 가지 못하게 했는데 더 좋은 방법이 있다면 알려주세요 !!!
|light mode|dark mode|등록한 컨텐츠가 없는 경우|
|![Simulator Screen Shot - iPhone 14 - 2022-11-30 at 03 57 57](https://user-images.githubusercontent.com/76623853/204622348-04ef552b-9d67-495b-bf35-93078f3e476f.png)|![Simulator Screen Shot - iPhone 14 - 2022-11-30 at 03 57 52](https://user-images.githubusercontent.com/76623853/204622375-3314f516-8ba0-4fc9-ab0d-12324d177fdf.png)|![Simulator Screen Shot - iPhone 14 - 2022-11-30 at 03 58 …

[Feat] 다른 사용자 프로필 화면 구현

---

HappyAnding/HappyAnding.xcodeproj/project.pbxproj
HappyAnding/HappyAnding/ViewModel/ShortcutsZipViewModel.swift
HappyAnding/HappyAnding/Views/ExploreCurationViews/ReadUserCurationView.swift
HappyAnding/HappyAnding/Views/HappyAndingApp.swift
HappyAnding/HappyAnding/Views/LaunchScreenView.swift
HappyAnding/HappyAnding/Views/MyPageViews/EditNicknameView.swift
HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutHeaderView.swift
HappyAnding/HappyAnding/Views/ShortcutsZipView.swift

- closes #338 
- 로그인 정보가 없을 때, 로그인 페이지로 이동하도록 설정하였습니다.
https://user-images.githubusercontent.com/68676844/205080495-d6e52c7b-99f7-43be-b260-dca4b8838a70.mov
- fetchUser 할 때, 현재 로그인한 유저인지 확인 후 signInStatus를 변경하였습니다.
- 런치 스크린 화면에서 로그인 페이지로 바로 전환하기 위해서 뷰모델 초기화 위치를 변경하였습니다.
- 로그인없이 둘러보기가 생긴다면, 삭제되어야합니다.

[Feat] user 정보가 없을 때, 로그인 화면으로 이동시키는 기능 구현

---

HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutTagView.swift
HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutTitleView.swift

- closes #353
- 단축어 링크 텍스트필드의 100자 길이제한을 해제했습니다.
- 카테고리 선택 UI가 글자가 길어지면 깨지던 문제를 해결했습니다.
|텍스트필드|카테고리|
|:---:|:---:|
|<img width="352" alt="Screenshot 2022-12-03 at 4 11 33" src="https://user-images.githubusercontent.com/94854258/205368098-813a56e2-404c-4f31-9f8e-5db4b14bc1fe.png">|<img width="345" alt="Screenshot 2022-12-03 at 4 11 49" src="https://user-images.githubusercontent.com/94854258/205368059-f394f89e-dd1f-4465-b697-ff5f23291026.png">|
- 해당PR의 코드 변경은 ShareExtension에 사용되는 뷰에도 똑같이 적용될 예정입니다.
- 관련 앱 작성 이후에는 다시 수정할 수 없고 해당 내용을 지운 뒤 만들어야 하는 이슈가 발견되어 추후 수정 예정으로, 현재는 TODO로 표시만 해 두었습니다.

WriteShortcutsView UI 수정

---

HappyAnding/HappyAnding/Views/Components/UserCurationCell.swift
HappyAnding/HappyAnding/Views/ExploreCurationViews/ReadUserCurationView.swift
HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationInfoView.swift
HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationSetView.swift

- closes #357 
- 큐레이션 작성 시 선택 가능한 단축어 가나다순 정렬
- 큐레이션 상세 화면에서 보여주는 단축어 가나다순 정렬
|iPhone 13|iPhone 13|
|:---:|:---:|
|![IMG_3795](https://user-images.githubusercontent.com/41153398/205436804-76c87d37-331c-4b80-82a7-e0e95cfec843.PNG)|![IMG_3796](https://user-images.githubusercontent.com/41153398/205436811-66734278-bcc2-4ca5-8b04-86d0ee9c1d73.PNG)|

[Feat] 큐레이션의 단축어 정렬 기능 추가

---

HappyAnding/HappyAnding/Views/ExploreCurationViews/ReadUserCurationView.swift
HappyAnding/HappyAnding/Views/MyPageViews/MyPageView.swift
HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutCommentView.swift
HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutHeaderView.swift
HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutView.swift
HappyAnding/HappyAnding/Views/ShortcutDetailViews/ShowProfileView.swift

- closes #356
- 앱에서 사용되는 모든 profile 이미지의 모양을 person.crop.circle.fill, medium, Gray3 로 통일했습니다.
|||||
|:---:|:---:|:---:|:---:|
|![KakaoTalk_Photo_2022-12-03-20-33-54 004](https://user-images.githubusercontent.com/94854258/205438905-a9192b17-66b1-4c33-9ea6-ac0c2595ef38.png)|![KakaoTalk_Photo_2022-12-03-20-33-54 003](https://user-images.githubusercontent.com/94854258/205438940-1b8074c0-a1ca-4d27-b93e-7e3c445e0f2f.png)|![KakaoTalk_Photo_2022-12-03-20-33-54 002](https://user-images.githubusercontent.com/94854258/205438951-4951764c-88b3-4d0f-aaa2-c9b4f3318628.png)|![KakaoTalk_Photo_2022-12-03-20-33-53 001](https://user-images.githubusercontent.com/94854258/205438963-99badea8-07aa-4bc0-9018-f56ce4bec945.png)|

Profile icon 이미지 통일

---

HappyAnding/HappyAnding/Views/Components/AdminCurationCell.swift
HappyAnding/HappyAnding/Views/ExploreCurationViews/ReadAdminCurationView.swift

- closes #366
- closes #367
- AdminCuration의 Subtitle이 한 줄 이상일때 가운데 정렬이 되는 오류를 좌측 정렬로 수정했습니다.
- AdminCuration의 Subtitle에 개행이 필요할 때를 대비해 개행문자를 변환하는 코드를 추가했습니다.

[Feat] Admin curation cell/description UI 오류 수정 및 개행문자 변환

---

HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutHeaderView.swift

- closes #360
- 좋아요를 나타내는 새로운 변수를 선언하여 문제를 해결했습니다.
https://user-images.githubusercontent.com/68676844/210176680-dcc7355e-e698-4f7a-8d67-e21219cffb3a.mov
- Heap 영역에 데이터를 저장해야하나 생각했었는데, 생각해보니 업데이트 화면에 들어가더라도, 인스턴스는 계속 살아있더라구요! 그래서 변수를 새로 선언하는 방법으로 문제 해결했습니다.
- numberOfLike라는 변수 선언 -> onAppear에서 shortcut에 저장되 좋아요 수로 초기화
- Button 누르면 삼항연산자를 통해 계산 -> onDisappear에서 shortcut에 값 저장 하는 로직으로 해결했슴다
- 저희 고려해야할 점이 있어요! 지금은 버튼을 누르는 순간이 아니라, 뷰가 사라질 때 값이 저장되고 있습니다.
그때 하트를 실수로 눌렀을 때의 비용 때문에 이렇게 설계했던 걸로 알고 있어요!
그런데 하트를 누르고 앱을 종료하는 경우, 제대로 저장되지 않기 때문에 앱 생명주기에 맞춘 저장 로직이 새로 필요할 것 같아요~! 관련 캡처화면 하단에 첨부합니다~
https://user-images.githubusercontent.com/68676844/210176696-89f7e9f5-ce92-4270-8f31-10f7bb957daa.mov

[Fix] #360 - 좋아요 수 업데이트

---

HappyAnding/HappyAnding/Views/Components/MyShortcutCardListView.swift
HappyAnding/HappyAnding/Views/Components/ShortcutCell.swift
HappyAnding/HappyAnding/Views/Components/UserCurationListView.swift
HappyAnding/HappyAnding/Views/ExploreCurationViews/ExploreCurationView.swift
HappyAnding/HappyAnding/Views/MyPageViews/MyPageView.swift
HappyAnding/HappyAnding/Views/MyPageViews/SettingView.swift
HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutCommentView.swift
HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutHeaderView.swift
HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutVersionView.swift
HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutView.swift
HappyAnding/HappyAnding/Views/ShortcutsZipView.swift
HappyAnding/HappyAnding/Views/SignInViews/SignInWithAppleView.swift

- closes #371
- 로그인 화면에 '로그인 없이 둘러보기' 버튼 추가
- 비로그인 상태에서 제거, 비활성화, Alert을 표시하는 기능들
- ReadShoercutsView의 좋아요, 다운로드, 이전 버전 다운로드 버튼 클릭 시 로그인 필요 Alert 추가
- ReadShoercutsView의 답글 버튼 제거, 댓글 달기 워딩 변경 및 비활성화
- 추천모음집 탭의 사용자를 위한 추천 모음집 항목 제거
- 프로필 탭의 닉네임을 '사용자' 로 변경 및 닉네임 수정 버튼 제거
- 프로필 탭의 단축어 작성, 추천 모음집 작성 버튼 클릭 시 로그인 필요 Alert 추가
- 프로필 탭 설정 화면의 로그아웃, 탈퇴하기 버튼 대신 로그인 버튼 표시
- Alert의 '로그인하기' 버튼 클릭 시 로그인 화면 표시
모두 로그인 없이 둘러보기 시 표시되는 화면입니다.
로그인 상태의 화면은 이전과 달라진 항목이 없습니다.
|로그인 화면|로그인 Alert|프로필 화면|설정 화면|댓글 화면|
|:---:|:---:|:---:|:---:|:---:|
|![Simulator Screen Shot - iPhone 14 Pro - 2023-01-08 at 00 58 38](https://user-images.githubusercontent.com/94854258/211159622-bd025a2d-97ba-46f0-985c-7c80e36352be.png)|![Simulator Screen Shot - iPhone 14 Pro - 2023-01-08 at 00 58 …

[Feat] #371 로그인 없이 둘러보기

---

HappyAnding/HappyAnding.xcodeproj/project.pbxproj
HappyAnding/HappyAnding/Extensions/LineBreaking+Extension.swift
HappyAnding/HappyAnding/Views/Components/ShortcutCell.swift
HappyAnding/HappyAnding/Views/Components/UserCurationCell.swift

- closes #323
- ShortcutsCell의 Subtitle이 충분한 공간이 있음에도 빨리 줄바꿈되는 문제를 해결했습니다.
- UserCurationCell의 Subtitle에도 기기에 따라 같은 문제가 있을 수 있어 미리 같은 방법으로 처리해두었습니다.
- Apple의 줄바꿈 방식 때문에 특정 경우에서 충분한 공간이 있음에도 줄바꿈이 되는 경우가 발생합니다.
- UIkit의 UILabel에서는 다음과 같은 방법으로 해당 설정을 해제할 수 있지만 SwiftUI에서는 지원하지 않습니다.
- `label.lineBreakStrategy = NSParagraphStyle.LineBreakStrategy()`
- 참조 : https://stackoverflow.com/questions/72685881/swiftui-text-doesnt-fit-full-width-while-having-multiple-lines
- text 뒤에 후행 공백을 충분히 넣으면 해결됩니다.
- 후행 공백을 넣는 `LineBreaking+Extension`을 만들어 적용했습니다.
|해결 이전|해결 이후|
|:---:|:---:|
|![Simulator Screen Shot - iPhone 14 Pro - 2023-01-20 at 03 01 46](https://user-images.githubusercontent.com/94854258/213526298-d455f97e-10f5-45c7-8781-aa4538350dc5.png)|![Simulator Screen Shot - iPhone 14 Pro - 2023-01-20 at …

[Fix] ShortcutCell, CurationCell의 줄바꿈 문제 해결

---

HappyAnding/HappyAnding/Views/TabView/ShortcutTabView.swift

- closes #363
- sheet의 고질적인 문제여서 Navigation으로 변경하여 문제를 해결하였습니다.
https://user-images.githubusercontent.com/68676844/214092052-24fd879f-2a1d-411f-bdad-68b2d99f612e.mov
- Navigation Path를 통해 구현했기 때문에, 만약 링크를 여러번 클릭하게 된다면, 그만큼 뷰가 쌓이게 됩니다! (이해가 어려우시다면, 스크린샷 추가하겠습니다)
- sheet에서 State를 사용하는 경우, 첫 화면에서 빈 화면이 나타나는 이슈가 존재한다. (iOS 14부터 존재하는 이슈로 확인됨)
- [참조](https://developer.apple.com/forums/thread/659660)에 따르면 State 변수가 예측하기 힘든 상황에서는 데이터가 제대로 작동하지 않는다고 한다. (정확한 문서나 답변은 찾지 못했다)
- 이를 해결하기 위해서 Sheet에 전달하는 데이터는 State가 아닌 Binding으로 전달해야한다.
- 현재 뷰가 State로 선언되어있으며, Binding으로 변경하기 애매한 상황이다. (Read Shortcuts View, Read Curation View) 모두 작업을 진행해야함 + 참조하는 페이지가 많아서
- 이에 팀원들과 논의 후 Navigation으로 진행하거나, Binding으로 선언한 새로운 뷰를 선언하여 작업을 진행할 예정이다. (현재는 Navigation으로 변경한 상태임)
- 현재 탭뷰를 사용하고 있어서, 3개의 Navigation Path를 선언해서 …

[Fix] 앱이 백그라운드에 없을 때, 비어있는 모달이 출력되는 문제

---

HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutHeaderView.swift

- closes #398 
- 탈퇴한 회원이 작성한 단축어 글의 좋아요 숫자가 제대로 보이지 않는 문제 해결
- 탈퇴한 회원의 경우 유저 정보가 존재하지 않아 값이 반환되는 클로저가 실행되지 않았고, 기존에는 처음 좋아요 숫자를 가져오는 동작을 해당 클로저 안에서 실행하여 발생한 문제 -> 좋아요 숫자를 가져오는 위치를 클로저 밖으로 변경하여 해결
| | |
|:---:|:---:|
|![Simulator Screen Shot - iPhone 13 - 2023-02-20 at 21 29 20](https://user-images.githubusercontent.com/41153398/220108353-b0a8fdf5-0331-4953-a82e-4fdce9f221b0.png)|![Simulator Screen Shot - iPhone 13 - 2023-02-20 at 21 29 31](https://user-images.githubusercontent.com/41153398/220108377-4539283e-3045-41bb-8069-7c219eaeebb2.png)|

[Fix] 좋아요 숫자 오류 해결

---

HappyAnding/HappyAnding/TextLiteral.swift
HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutView.swift

- closes #383 
- 댓글 입력 시 줄바으로 인해 댓글입력창이 무제한으로 늘어나는 이슈를 해결했습니다.
- 댓글을 입력할때는 4줄까지, 답글을 입력할때는 2줄까지 텍스트필드가 늘어나도록 했습니다.
- 줄바꿈은 계속 가능하며, 텍스트필드 스크롤 또한 가능합니다.
- 3회 이상의 줄바꿈을 제한하는 기능도 생각해 봤지만 의미가 있을지, 어떻게 막을지에 대한 고민이 생겨서 구현하지 않았습니다.
- 위의 기능이나 다른 기능들 추가가 필요하다고 생각되면 추가하겠습니다!

[Fix] 댓글입력 창 레이아웃 오류 해결

---

HappyAnding/HappyAnding.xcodeproj/project.pbxproj
HappyAnding/HappyAnding/Views/MyPageViews/SettingViews/LicenseView.swift
HappyAnding/HappyAnding/Views/MyPageViews/SettingViews/wrappinghstack+license.txt
HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutContentView.swift

- closes #386 
- ReadShortcutContentView에서 '카테고리'와 '단축어 사용에 필요한 앱' 레이아웃을 변경 및 통일했습니다.
- 컨텐츠의 길이에 맞춰 변화하는 여러줄의 hstack을 표현하기 위해 오픈소스를 사용했습니다. (사용된 패키지 - https://github.com/dkk/WrappingHStack) 이후에 제 코드로 수정해보겠습니다 ~!
- MIT license 파일 추가했습니다.
|![Simulator Screen Shot - iPhone SE (3rd generation) - 2023-02-20 at 22 54 23](https://user-images.githubusercontent.com/76623853/220126644-95ef77ce-c720-4a1a-98bf-d11c72258383.png)|![Simulator Screen Shot - iPhone 14 - 2023-02-20 at 18 23 47](https://user-images.githubusercontent.com/76623853/220126510-4cc25ed5-719f-4adc-b176-229ce6053818.png)|![Simulator Screen Shot - iPhone 14 Pro Max - 2023-02-20 at 22 55 51](https://user-images.githubusercontent.com/76623853/220127024-28174ee3-e87a-4c6d-9864- …

[Feat] 카테고리를 표현하는 레이아웃 변경

---

HappyAnding/HappyAnding/Views/MyPageViews/SettingView.swift

- closes #403
- 기존에는 수동으로 관리되던 SettingView의 버전 정보를 Bundle에서 가져와서 보여주는 방빅으로 변경했습니다.
- SettingView에 `getAppVersion` 함수에서 Bundle에 있는 app Version을 가져와 표시합니다.
- 디자인적인 변경사항은 없습니다.
- 코드리뷰 후 추가적인 변경사항
- 오류로 인해 버전정보를 가져오지 못할 경우 버전정보 항목을 보이지 않게 처리했습니다.

[Feat] 버전정보 처리방법 변경

---

HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutVersionView.swift

- closes #417
- ReadShortcutVersionView에서 버전 정보 텍스트가 한 줄을 넘어갈 경우 잘리는 레이아웃 오류를 해결했습니다.
- 버전 정보를 보여주는 셀 아래 Spacer의 속성인 `frame(maxHeight: .infiinity)가 원인이었습니다.
- 해당 Spacer는 정보가 위쪽에 배치될 수 있도록 하는 역할을 수행하는데, 여기에 최대높이가 .infinity로 설정되면서 해당 이슈가 나타났습니다.
- Spacer의 최대 높이 설정으로 인해 버전 정보 셀의 설명 텍스트의 높이가 최소한으로 줄어버려(1줄만 표시될 수 있도록) 2줄인 경우에는 표시가 온전하게 되지 않은 것으로 보입니다.
- 그런데 아무런 frame 속성이 붙지 않은 Spacer도 자신의 높이를 최대로 세팅하는 것으로 알고 있는데, 왜 .infinity 속성을 붙여 주었을 때만 해당 이슈가 나타나는지는 파악하지 못했습니다.
|개선 전|개선 후|
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/94854258/222900457-4ae7d2a3-2b9f-4e5a-befc-f962988208f7.png)|![Simulator Screen Shot - iPhone 14 Pro - 2023-03-04 at 21 11 44](https://user-images.githubusercontent.com/94854258/222900477-e1e4b63f-bccd-419f-bb41-ae6a52acaec0.png)|

[Fix] 단축어 버전 정보 화면의 레이아웃 오류 해결

---

HappyAnding/HappyAnding.xcodeproj/project.pbxproj
HappyAnding/HappyAnding/Extensions/View/View+Navigation.swift
HappyAnding/HappyAnding/Model/NavigationStackModel.swift
HappyAnding/HappyAnding/Views/Components/UserCurationListView.swift
HappyAnding/HappyAnding/Views/ExploreCurationViews/ReadUserCurationView.swift
HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationInfoView.swift
HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationSetView.swift

- closes #426
- iOS 16.1부터 추천 모음집 작성 시 앱이 꺼졌던 이유는 Navigation Stack Path 모델을 전달해주지 않았기 때문이었습니다.
- Navigation Path 초기화의 경우 iOS 16.1부터 작동하도록 수정했습니다.
- iOS 16.0애서 추천 모음집 작성 시 빈 화면이 나왔던 이유는 Navigation Router에 해당 Data 정보가 없었기 때문입니다.
- 현재 추천모음집이 Full Screen Cover로 presented라는 바인딩 변수가 필요합니다. 하지만 저희 프로젝트의 경우 Navigation Router를 통해 데이터를 한 번에 관리하고 있어서 함수를 오버로딩 하여 문제를 해결했습니다.
- 이와 같이 데이터가 누락되는 문제를 해결하기 위해서는 Navigation Data 전체를 다루는 열거형으로 정의하는 것이 좋을 것 같습니다
- 추천 모음집 작성시 앱이 종료되는 문제 (iOS 16.1부터)해결
- 추천 모음집 작성시 빈 페이지가 나오는 문제 (iOS 16) 해결
https://user-images.githubusercontent.com/68676844/224933852-146b6e75-9610-4700-8d64-cd690624ce60.mov
https://user-images.githubusercontent.com/68676844/224934035-bd0a7207-edde-4faa-b18a-2d0d77220be7.mov

[Fix] #426 - 네비게이션 오류 해결

---

HappyAnding/HappyAnding/Views/ExploreCurationViews/ListCurationView.swift
HappyAnding/HappyAnding/Views/MyPageViews/MyPageView.swift
HappyAnding/HappyAnding/Views/MyPageViews/SettingView.swift

- closes #423 
- Apple로부터 디자인 피드백을 받은 사항을 반영했습니다.
- 프로필 탭 닉네임의 오른쪽에 위치해 있던 닉네임 수정 버튼을 설정 페이지 안쪽으로 이동시켰습니다.
- 사용자가 설정히는 항목이기 때문에 위치는 버전 정보 바로 아래, 최상단으로 설정했습니다.
- 항목이 늘어남에 따라 VStack에서 ScrollView로 변경해 화면보다 항목이 길어질 경우를 대비했습니다.
- 현재 해당 ScrollView 내부에 컴포넌트가 10개 이상 사용됨에 따라 컴파일 에러가 발생했습니다. 같은 종류의 컴포넌트들을 Group으로 묶어 해결했는데, 더 좋은 방법이 있다면 제안해주시면 감사하겠습니다!
- 닉네임 수정 뷰가 나타나는 방식을 Navigation에서 Modal로 변경했습니다.
- 이에 따라 NavigationRouter에서 EditNicknameView 관련 코드를 삭제해도 무방할 것 같은데 괜찮을까요?
- 작성한 단축어 또는 추천 모음집이 없을 때 나타나는 텍스트의 조사를 '이(가)'에서 나타나는 텍스트에 맞게 자연스럽게 나타날 수 있도록 수정했습니다. 다음과 같이 표시됩니다.
- 아직 내가 작성한 추천 모음집이(가) 없어요 -> 아직 내가 작성한 추천 모음집이 없어요
- 텍스트 안에 '단축어' 가 있으면 '가' 를, 없으면(추천 모음집) '이' 를 붙입니다.
- 현재 해당 뷰에 들어가는 텍스트가 단추축어, 추천 모음집 둘 중  하나로 끝나기 때문에 이렇게 처리해도 문제가 되지 않을 것으로 생각했습니다.
- 이런 식으로 조사를 처리하는 경우가 추후 앱에서 많이 사용될 것 같다면, 텍스트의 …

[Feat] 닉네임 수정 버튼 위치 변경 등의 UI 변경사항 (Apple Feedback)

---

HappyAnding/HappyAnding/Views/ShortcutDetailViews/ShowProfileView.swift

- closes #425
- ShowProfileView에서 유저의 badge를 터치했을 때의 인터렉션을 추가했습니다. 오른쪽 방향으로 한 바퀴 badge가 회전합니다.
- 회전 반동은 AboutShortcutGradeView와 같은 정도로 주었습니다.
- View가 onAppear 될 때도 오른쪽으로 한 바퀴 회전합니다.
|iPhone SE|iPhone 14|
|:---:|:---:|
| https://user-images.githubusercontent.com/94854258/236709833-5c41f1bc-1661-410f-a7bb-42b9fc5c0b93.mp4 | https://user-images.githubusercontent.com/94854258/236709843-807583d1-fb75-4bee-a330-31f86aa4950e.mp4 |

[Feat] #425 ShowProfileView에서의 badge 회전 추가 (Apple Feedback)

---

HappyAnding/HappyAnding/Views/TabView/ShortcutTabView.swift

- closes #441
- 앱 로그인 시 간헐적으로 Red 컬러의 배경이 화면 전체에 보이는 버그를 해결했습니다.
- ShortcutTabView의 background 속성을 제거함으로 해결했습니다.

[bug] ShortcutTabView의 Red 배경색 제거

---

HappyAnding/HappyAnding.xcodeproj/project.pbxproj
HappyAnding/HappyAnding/Views/Components/UserNameCell.swift
HappyAnding/HappyAnding/Views/ExploreCurationViews/ReadUserCurationView.swift
HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutHeaderView.swift
HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutView.swift

- closes #439
- closes #422 
- ReadShortcutView와 ReadCurationView의 작성자 셀의 디자인을 통일합니다.
- 셀 오른쪽에 chevron을 추가
- 탈퇴한 사용자일 경우 chevron을 없애서 disabled 표현
- 작성자 셀 컴포넌트화
|ReadUserCurationVIew|ReadShortcutView|탈퇴한 사용자|
|<img src = "https://github.com/DeveloperAcademy-POSTECH/MacC-Team-HappyAnding/assets/41153398/0ced8eb1-62a4-473e-8017-e8b0e92a810e" width=200>|<img src ="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-HappyAnding/assets/41153398/02440afe-4423-441d-9674-a3509158cc83" width=200>|<img src ="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-HappyAnding/assets/41153398/bc879708-c100-4ed8-96fd-c8d17118fac5" width=200>|

[Feat] 작성자 닉네임 셀 디자인 통일

---

HappyAnding/HappyAnding/Views/ShortcutDetailViews/ReadShortcutView/ReadShortcutView.swift
HappyAnding/HappyAnding/Views/ShortcutDetailViews/ShowProfileView.swift

- closes #432
- 커스텀 제스처로 인해 swipe back이 간헐적으로 동작하지 않는 문제를 해결했습니다.
현재 tabbar를 page 형태로 사용하고 있어서 드래그를 커스텀하지 않아도 탭의 변경이 가능한 상황입니다.
그래서 우선 커스텀했던 드래그만 삭제한 상황입니다. 제가 실기기로 테스트 했을 때에는 이전보다 확실히 나아진 것 같아요!
우선 테스트 해 보시고, 불편하시다면 기본 드래그 제스처도 삭제하도록 하겠습니다!
- 프로필 보기 뷰와 단축어 상세 뷰의 탭 라인 위치를 통일시켰습니다.
|||
|---|---|
|<img src = "https://github.com/DeveloperAcademy-POSTECH/MacC-Team-HappyAnding/assets/68676844/18d6d9e5-4f06-4454-90a0-b8fff9d157bb" width = 250>|<img src = "https://github.com/DeveloperAcademy-POSTECH/MacC-Team-HappyAnding/assets/68676844/dec20639-d514-4070-a69a-eb59a8e13ce0" width = 250>
|

[Feat] Swipe 제스처 삭제 

---

HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView/LovedShortcutView.swift
HappyAnding/HappyAnding/Views/ShortcutDetailViews/UpdateShortcutView.swift
HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationInfoView.swift
HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutView.swift

- closes #387 
- closes #382 
- 포커스를 가진 텍스트필드가 키보드에 가려지지 않도록 합니다.
- `@FocusState`를 사용하여 return키로 다음 텍스트필드로 이동할 수 있습니다.
- WriteShortcutView, UpdateShortcutView, WriteCurationInfoView에서 동작 확인해주시면 됩니다.
- `@FocusState`가 Sheet 위에서 잘 동작하지 않는 이슈가 있습니다.
- ShareExtension의 텍스트필드에서는 `@FocusState`를 사용하지 않으셨던데 그래서 그런건가요? 😭
- ShareExtension은 따로 이슈를 파서 다음 업데이트에 포함해야 할 것 같습니다.
https://github.com/DeveloperAcademy-POSTECH/MacC-Team-HappyAnding/assets/76623853/23efde08-6df6-427b-b400-46606a307da8

[Feat] TextEditor Keyboard Avoidance

---

HappyAnding/HappyAnding.xcodeproj/project.pbxproj
HappyAnding/HappyAnding/Extensions/View/View+Navigation.swift
HappyAnding/HappyAnding/Model/Curation.swift
HappyAnding/HappyAnding/Model/NavigationStackModel.swift
HappyAnding/HappyAnding/Model/User.swift
HappyAnding/HappyAnding/ViewModel/ExploreCurationViewModels/ExploreCurationViewModel.swift
HappyAnding/HappyAnding/ViewModel/ExploreCurationViewModels/ListCurationViewModel.swift
HappyAnding/HappyAnding/ViewModel/ExploreCurationViewModels/ReadCurationViewModel.swift
HappyAnding/HappyAnding/ViewModel/ReadCurationViewModel.swift
HappyAnding/HappyAnding/ViewModel/ShortcutsZipViewModel.swift
HappyAnding/HappyAnding/Views/Components/UserCurationCell.swift
HappyAnding/HappyAnding/Views/Components/UserCurationListView.swift
HappyAnding/HappyAnding/Views/Components/UserNameCell.swift
HappyAnding/HappyAnding/Views/ExploreCurationViews/ExploreCurationView.swift
HappyAnding/HappyAnding/Views/ExploreCurationViews/ListCurationView.swift
HappyAnding/HappyAnding/Views/ExploreCurationViews/ReadCurationView.swift
HappyAnding/HappyAnding/Views/HappyAndingApp.swift
HappyAnding/HappyAnding/Views/ReadShortcutViews/ShowProfileView.swift
HappyAnding/HappyAnding/Views/TabView/ShortcutTabView.swift
HappyAnding/HappyAnding/Views/WriteCurationViews/WriteCurationSetView.swift

- closes #468 #472
- Read Curation View Model 생성했습니다.
- 특정 모델에 init 함수를 정의해서 조금 편하게 쓸 수 있도록 수정했습니다.
- viewModel의 의존성은 Navigation Stack에서 제공합니다
- 63370d5bbf2ae2afd2d30bad4755663048b0d6b3 의 경우, 그린이 작업해주신 부분인데 같이 수정해서 업로드합니다.
- Explore Curation Views에 대한 View Model 생성
- Navigation Stack Curation.self, CuratonType.self로 수정
뷰 변경사항은 없습니다.
- 수정 후 cell의 업데이트 일어나지 않음
- UserCurationCell에 선언된 curation을 Binding으로 변경해야합니다.

[Feat] Explore curatoin view model 적용

---

HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView.swift
HappyAnding/HappyAnding/Views/ExploreShortcutViews/ListCategoryShortcutView.swift
HappyAnding/HappyAnding/Views/ExploreShortcutViews/ListShortcutView.swift

- closes #471 
- ExploreShortcutViewModel, ListShortcutViewModel, ListCategoryShortcutViewModel 생성했습니다.
- ExploreShortcutView 파일 위치 수정했습니다. bf10a440159816a347491f0aefaea15c74fc0022
- 불필요해 보이는 뷰모델이나 변수, 함수가 있다면 의견주세요 !!!
화면상 변경사항 없음

[Feat] ExploreShortcutViewModel 생성

---

HappyAnding/HappyAnding.xcodeproj/project.pbxproj
HappyAnding/HappyAnding/Views/WriteShortcutViews/IconModalView.swift

- closes #484
- IconModalView의 아이콘 태그 색상이 다크모드에서 의도된 디자인대로 나오지 않는 뷰 코드 실수를 수정했습니다.
- 동일 뷰 상단의 아이콘을 고정해, 아이콘 수정 시 직관적으로 수정할 수 있게 했습니다. 
|다크 모드|라이트 모드|
|:---:|:---:|
|![IMG_0584](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-HappyAnding/assets/94854258/497d9883-fa66-4c8b-8a7b-1d4ce4deaa45)|![IMG_0585](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-HappyAnding/assets/94854258/f65a7855-1759-468f-b1a5-a1352558010d)|

[Fix] IconModalView의 태그 색상 수정 등

---

HappyAnding/HappyAnding.xcodeproj/project.pbxproj
HappyAnding/HappyAnding/TextLiteral.swift
HappyAnding/HappyAnding/Views/ReadShortcutViews/ReadShortcutView.swift

- closes #447
- 단축어 상세 정보 페이지에 단축어 작성 날짜 표시
- 업데이트 시 업데이트 날짜로 표시
- 단축어 댓글 페이지에 댓글 작성 날자 표시
- 댓글이 최근에 달렸을 경우 x시간 전, x일 전 등의 레이블을 다는 것에 대해 논의해보면 좋을 것 같습니다!
- 디자인 부분에서 수정 관련 아이디어가 있다면 코멘트 달아주세요.
|단축어 상세 정보 날짜|댓글 작성 날짜|
|:---:|:---:|
|![Simulator Screenshot - iPhone 14 Pro - 2023-07-28 at 19 02 47](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-HappyAnding/assets/94854258/dbb55cca-eb68-44fa-b095-b1edf6945488)|![Simulator Screenshot - iPhone 14 Pro - 2023-07-28 at 19 03 49](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-HappyAnding/assets/94854258/5deb87c1-03c3-4d91-8db3-9f49807ff2a8)|

[Feat] 단축어 및 댓글에 날짜 표시

---

HappyAnding/HappyAnding/Views/Components/ShortcutCardCell.swift

- closes #496
- 기존 ShortcutCardCell에서 텍스트가 한 줄만 보이던 문제를 해결했습니다.
- 원인
- 기존에도 Cell 내부 Text의 Linelimit는 2줄까지로 되어 있었습니다.
- Cell 내부 공간이 텍스트가 2줄이 배치될 만큼 충분하지 않아서 해당 문제가 발생했습니다.
- 내부 Padding을 줄여도 같은 문제가 지속되었습니다.
- 해결 및 변경사항
- Cell의 세로를 104 -> 112로 늘려 해결했습니다.
- Cell의 크기를 고정하고 텍스트의 크기를 headline(17)에서 subtitle(15)로 줄여도 문제가 해결되지 않아 차선책으로 Cell의 크기를 늘렸습니다.
- #377 혹시나 나타날 수 있는 해당 문제를 방지하기 위해 .linebreaking extension도 적용했습니다.
|수정 전|수정 후|
|:---:|:---:|
|![image](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-HappyAnding/assets/94854258/3744a108-93f7-4564-a9d9-e45ee03f63af)|![Simulator Screenshot - iPhone 15 Pro - 2023-10-13 at 22 48 36](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-HappyAnding/assets/94854258/08e72747-1bbf-439d-ba1c-993997e21641)|

[Fix] ShortcutCardCell 두 줄 표시 안 되는 문제 해결

---

HappyAnding/HappyAnding/Views/Components/ShortcutCell.swift
HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView.swift
HappyAnding/HappyAnding/Views/ExploreShortcutViews/ListShortcutView.swift

- closes #495
- [ExploreShortcutView](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-HappyAnding/pull/461) 코드가 일원화된 이후 rankNumber가 정상적으로 표시되지 않던 오류를 해결했습니다.
- 단축어 탭의 다운로드 순위 섹션에서만 rankNumber가 표시됩니다.
- 다운로드 순위 섹션에서 ListShortcutView에 접근했을 경우에만 rankNumber가 표시됩니다.
- 추가 구현 사항
- ListShortcutView의 상단 padding이 존재하지 않던 오류를 해결했습니다. 
- ListShortcutView의 하단 padding 구현 방식을 효율적으로 개선했습니다.
| 단축어 탭 | ListChortcutView |상단 Padding|
| ![Simulator Screenshot - iPhone 15 Pro - 2023-10-14 at 16 22 11](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-HappyAnding/assets/94854258/2af315d6-5dc0-487a-a08b-1e9b837fc931) | ![Simulator Screenshot - iPhone 15 Pro - 2023-10-14 at 16 22 18](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-HappyAnding/assets/94854258/82f119d6-f215-430f-b …

[Fix] 단축어 탭 ShortcutCell의 rankNumber 표시 오류 해결

---

HappyAnding/HappyAnding.xcodeproj/project.pbxproj
HappyAnding/HappyAnding/Support/HapticManager.swift
HappyAnding/HappyAnding/Views/Components/GradeAlertView.swift
HappyAnding/HappyAnding/Views/Components/NicknameTextField.swift
HappyAnding/HappyAnding/Views/Components/ShortcutCell.swift
HappyAnding/HappyAnding/Views/Components/ValidationCheckTextField.swift
HappyAnding/HappyAnding/Views/ExploreShortcutViews/ExploreShortcutView.swift
HappyAnding/HappyAnding/Views/FeatureViews/AboutShortcutGradeView.swift
HappyAnding/HappyAnding/Views/ReadShortcutViews/ReadShortcutView.swift
HappyAnding/HappyAnding/Views/ReadShortcutViews/ShowProfileView.swift
HappyAnding/HappyAnding/Views/ReadShortcutViews/UpdateShortcutView.swift
HappyAnding/HappyAnding/Views/TabView/ShortcutTabView.swift
HappyAnding/HappyAnding/Views/WriteShortcutViews/WriteShortcutView.swift
HappyAnding/ShareExtension/CustomShareViewController.swift
HappyAnding/ShareExtension/ShareExtensionValidationTextField.swift

- closes #492
- 앱 곳곳에 Haptic Feedback을 추가해 UX를 개선했습니다.
- Haptic은 싱글톤 형태로 구현했고, Haptic을 위한 HapticManager 파일은 HappyAnding 디렉토리 안 Extension 다음에 `Support` 그룹을 만들어 넣었는데, 더 좋은 방법이 있다면 제안해주세요!
- Haptic을 적용하는 동작/버튼 선정 기준은 다음과 같습니다.
- 앱의 주요 동작을 수행하는 버튼/동작
- 사용자가 수행되었음을 분명하게 인지하는 것이 필요한 동작
- Haptic이 적용된 곳은 다음과 같습니다. 화살표 우측은 Haptic의 종류입니다.
1. ShortcutTabView
1. 3개의 탭바 버튼 → light
2. ShortcutCell
1. download icon → success
3. ValidationCheckTextField
1. error 시 → error
4. NicknameTextField
1. error 시 → error
5. GradeAlertView
1. 레벨업 시 → success
6. WriteShortcutView
1. 업로드 탭 시 → success
7. ReadShortcutView
1. download icon → success 
2. 하트 탭 시 → rigid
8. UpdateShortcutView
1. 업로드 탭 시 → success
9. ShowProfileView
1. icon 탭 시 → rigid
10. AboutShortcutGradeView
1. icon 탭 시 → rigid
11. …

[Feat] 햅틱 피드백 추가

---

HappyAnding/HappyAnding/Views/ReadShortcutViews/ReadShortcutView.swift

- closes #502 
- 댓글에서도 hypertext 를 사용할 수 있게 .init을 추가했습니다.
- 해당 방법만 적용했을 때, 터치가 되지 않는 문제가 있어 .textSelection를 활성화했습니다.
- link의 색상은 .shortcutsZipPrimary로 적용했습니다.
|iPhone SE, 다크 모드|iPhone 15 pro, 라이트 모드|
|:---:|:---:|
| ![Simulator Screenshot - iPhone SE (3rd generation) - 2023-10-18 at 12 34 45](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-HappyAnding/assets/94854258/63768be9-0f92-4734-9feb-0ce832db0012) | ![Simulator Screenshot - iPhone 15 Pro - 2023-10-18 at 12 32 50](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-HappyAnding/assets/94854258/eb821e2d-c32f-4fcd-b9ea-10d789f5eb37) |

[Feat] 댓글 Copy 및 hypertext 추가
